<a href="https://colab.research.google.com/github/MartinVIllesca/CC6205-Procesamiento-de-Lenguaje-Natural/blob/master/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 1 NLP : Competencia de Clasificación de Texto
-------------------------------


- **Nombre:** Jou-Hui Ho Ku, Martín Valderrama

- **Usuario o nombre de equipo en Codalab:** PibJou




## Objetivo e Instrucciones:

### Objetivo

Esta tarea consiste en participar en una competencia cuyo objetivo es la clasificación de tweets según su intensidad de emoción. Específicamente: 

Tendrán 4 datasets de tweets de distintas emociones: `anger`, `fear`, `sadness` y `joy`. Para cada uno de estos datasets, deberán crear un clasificador que indique la intensidad de dicha emoción en sus tweets (`low`, `medium`, `high`).

###  Fecha de Entrega: 

Por ser anunciada una vez termine el paro. Se publicará la fecha en ucursos.

### Detalles e instrucciones de la competencia:

- La competencia consiste en resolver 4 problemas de clasificación distintos, cada uno de tres clases. Por cada problema deberán crear un clasificador distinto. La evaluación de la competencia se realiza en base a 4 métricas: AUC, Kappa y Accuracy. Los mejores puntajes en cada ítem serán los que ganen.

- Para comenzar se les entregará en este notebook el baseline y la estructura del reporte. El baseline es el código que realiza creación de features y clasificación básica. Los puntajes de este serán ocupados como base para la competencia: deben superar sus resultados para ser bien evaluados.  

- Para participar, deben registrarse en Codalab y luego ingresar a la competencia usando el siguiente [link]( https://competitions.codalab.org/competitions/24121?secret_key=f5eb2d95-b36e-4aad-8fc5-4d9d77f4e4dc). 

- **Es requisito entregar el reporte con el código y haber participado en la competencia para ser evaluado.**

- Pueden hacer grupos de máximo 2 alumnos. Cada grupo debe tener un nombre de equipo (En codalab, ir a settings y después cambiar Team Name). Solo una persona debe administrar la cuenta del grupo.

- En total pueden hacer un **máximo de 4 envíos/submissions** (tanto para equipos como para envíos indivuales).

- Hagan varios experimentos haciendo cross-validation o evaluación sobre una sub-partición antes de enviar sus predicciones a Codalab. Asegúrense que la distribución de las clases sea balanceada en las particiones de training y testing. Verificar que el formato de la submission coincida con el de la competencia. De lo contrario, se les será evaluado incorrectamente.

- Estar top 5 en alguna métrica equivale a 1 punto extra en la nota final.

- No se limiten a los contenidos vistos ni a scikit ni a este baseline. ¡Usen todo su conocimiento e ingenio en mejorar sus sistemas! 

- Todas las dudas escríbanlas en el hilo de U-cursos de la tarea. Los emails que lleguen al equipo docente serán remitidos a ese medio.


### Reporte

Este debe cumplir la siguiente estructura:

1.	**Introducción**: Presentar brevemente el problema a resolver, los métodos y representaciones utilizadas en el desarrollo de la tarea y conclusiones obtenidas. (0.5 Puntos)
2.	**Representaciones**: Describir los atributos y representaciones usadas como entrada de los clasificadores. Si bien, con Bag of Words (baseline) ya se comienzan a percibir buenos resultados, pueden mejorar su evaluación agregando más atributos y representaciones diseñadas a mano. Mas abajo encontrarán una lista útil de estos que les podrá ser de utilidad. (1.5 puntos)
3.	**Algoritmos**: Describir brevemente los algoritmos de clasificación usados. (0.5 puntos)
4.	**Métricas de evaluación**: Describir brevemente las métricas utilizadas en la evaluación indicando que miden y su interpretación. (0.5 puntos)
5.	**Experimentos**: Reportar todos sus experimentos. Comparar los resultados obtenidos utilizando diferentes algoritmos y representaciones. Estos experimentos los hacen sobre la sub-partición de evaluación que deben crear (o pueden usar cross-validation). Incluyan todo el código de sus experimentos aquí. ¡Es vital haber realizado varios experimentos para sacar una buena nota! (2 puntos)
6.	**Conclusiones**: Discutir resultados, proponer trabajo futuro. (1 punto)

### Baseline

Por último, el baseline contiene un código básico que:

- Obtiene los dataset.
- Divide los datasets en train (entrenamiento y prueba) y target set (el que clasificar para subir a la competencia).
- Crea un Pipeline que: 
    - Crea features personalizadas.
    - Transforma los dataset a bag of words (BoW).  
    - Entrena un clasificador usando cada train set.
- Clasifica y evalua el sistema creado usando el test set.
- Clasifica el target set.
- Genera una submission con el target en formato zip en el directorio en donde se está ejecutando el notebook. 


Algunas pistas sobre como mejorar el rendimiento de los sistemas que creen. (Esto tendrá mas sentido cuando vean el código)

- **Vectorizador**: investigar los modulos de `nltk`, en particular, `TweetTokenizer`, `mark_negation` para reemplazar los tokenizadores. También, el parámetro `ngram_range` (Ojo que el clf naive bayes no debería usarse con n-gramas, ya que rompe el supuesto de independencia). Además, implementar los atributos que crean útiles desde el listado del el enunciado. Investigar también el vectorizador tf-idf.

- **Clasificador**: investigar otros clasificadores mas efectivos que naive bayes. Estos deben poder retornar la probabilidad de pertenecia de las clases (ie: implementar la función `predict_proba`).

- **Features**: Recuerden que pueden implementar todas las features que se les ocurra! Aquí les adjuntamos algunos ejemplos:
    -	Word n-grams.
    -	Character n-grams. 
    -	Part-of-speech tags.
    -	Sentiment Lexicons (Lexicon = A set of words with a label or associated value.).
        - Count the number of positive and negative words within a sentence.
        - If the lexicon has associated intensity of feeling (for example in a decimal), then take the average of the intensity of the sentence according to the feeling, the sum, etc.
        -	A good lexicon of sentiment: [Bing Liu](http://www.cs.uic.edu/~liub/FBS/opinion-lexicon-English.rar) 
        - A reference with a lot of [sentiment lexicons](https://medium.com/@datamonsters/sentiment-analysis-tools-overview-part-1-positive-and-negative-words-databases-ae35431a470c). 
    -	The number of elongated words (words with one character repeated more than two times).
    -	The number of words with all characters in uppercase.
    -	The presence and the number of positive or negative emoticons.
    -	The number of individual negations.
    -	The number of contiguous sequences of dots, question marks and exclamation marks.
    -	Word Embeddings: Here are some good ideas on how to use them.
    https://stats.stackexchange.com/questions/221715/apply-word-embeddings-to-entire-document-to-get-a-feature-vector

- **Reducción de dimensionalidad**: También puede serles de ayuda. Referencias [aquí](https://scikit-learn.org/stable/modules/unsupervised_reduction.html).

- Por último, pueden encontrar mas referencias de cómo mejorar sus features, el vectorizador y el clasificador [aquí](https://affectivetweets.cms.waikato.ac.nz/benchmark/).

(Pueden eliminar cualquier celda con instrucciones...)

**Importante**: Recuerden poner su nombre y el de su usuario o de equipo (en caso de que aplique) tanto en el reporte. NO serán evaluados Notebooks sin nombre.

----------------------------------------

(borrar este bloque despues)
1.	**Introducción**: Presentar brevemente el problema a resolver, los métodos y representaciones utilizadas en el desarrollo de la tarea y conclusiones obtenidas. (0.5 Puntos)
2.	**Representaciones**: Describir los atributos y representaciones usadas como entrada de los clasificadores. Si bien, con Bag of Words (baseline) ya se comienzan a percibir buenos resultados, pueden mejorar su evaluación agregando más atributos y representaciones diseñadas a mano. Mas abajo encontrarán una lista útil de estos que les podrá ser de utilidad. (1.5 puntos)
3.	**Algoritmos**: Describir brevemente los algoritmos de clasificación usados. (0.5 puntos)
4.	**Métricas de evaluación**: Describir brevemente las métricas utilizadas en la evaluación indicando que miden y su interpretación. (0.5 puntos)
5.	**Experimentos**: Reportar todos sus experimentos. Comparar los resultados obtenidos utilizando diferentes algoritmos y representaciones. Estos experimentos los hacen sobre la sub-partición de evaluación que deben crear (o pueden usar cross-validation). Incluyan todo el código de sus experimentos aquí. ¡Es vital haber realizado varios experimentos para sacar una buena nota! (2 puntos)
6.	**Conclusiones**: Discutir resultados, proponer trabajo futuro. (1 punto)

## 1. Introducción

El problema a abordar en este trabajo es el análisis de sentimientos de tweets. Se tiene un dataset de tweets clasificados por sentimiento (joy, fear, sadness, anger), y en cada sentimiento, a su vez, los tweets se clasifican por intensidad (alto, medio o bajo).

Para resolver este problema, se utilizan distintas representaciones de los datos, tales como Bag Of Words, la representación Tf-Idf, Word Embeddings, y también se extraen características relevantes de los textos, como por ejemplo la cantidad de signos de exclamación que contengan.

Una vez convertidos los textos a su representación, se utilizan métodos de NaiveBayes y SVM para clasificar el nivel de sentimiento en cada clase.

A partir de este trabajo, se concluye que....

## 2. Representaciones

Se implementan distintas representaciones de los textos, mediante las siguientes clases:

   
- **CountVectorizer** \
    Consiste en una representación de los textos en Bag of Words.
    
- **TfidfVectorizer**\
    Calcula la matriz Tf-Idf asociada al dataset. El algoritmo funciona sobre un tokenizer el cual por defecto se realiza separando solamente las palabras del tweet en este caso. Se puede utilizar con distintos Tokenizers, en esta tarea se prueba un caso con el TweetTokenizer de la librería nltk.
    
- **TweetTokenizer**\
    Es un tokenizer pre-definido de la librería nltk, el cual reconoce carácteres especiales de los mensajes de Twitter como emojis en símbolos o puntutación, incluso hashtags.
    

- **CharCountTransformer**: \
    Esta representación considera una serie de conteos "manuales" implementados a continuación. Esta incluye:
    - **Caracteres relevantes dentro del texto**, tales como:
        - Cantidad de signos de exclamación
        - Cantidad de signos de interrogación
        - Cantidad de letras repetidas más de tres veces
        - Cantidad de letras en mayúscula
        - Cantidad de puntos seguidos 
    - Se utiliza la librería _emoji_ para codificar los emojis de los tweets, y la librería _emosent_ para extraer un sentiment score del emoji, además de la polaridad del sentimiento. Cabe destacar que existen algunos emojis que no están en la librería _emosent_, por lo que fue necesario evaluar su polaridad bajo inspección, y evaluar si el nombre del emoji contiene palabras positivas o negativas.
    - Además, se marcan previamente las palabras que siguen a una negación, concatenando el string \_NEG luego de la palabra, para que sea considerada diferente a la misma palabra, pero en un contexto positivo.
 
- **Doc2VecTransformer** \
    Word embeddings con el modelo _glove_twitter_ ya entrenado. Se considera el máximo de cada tweet, considerando que se quiere realizar un análisis de sentimientos, y otras operaciones como suma o promedio podrían causar una pérdida de información.
    
- **LiuFeatureExtractor**\
    Extrae la cantidad de palabras positivas y palabras negativas, usando el dataset de Bing Liu.

- **VaderFeatureExtractor**\
    https://github.com/cjhutto/vaderSentiment

## 3. Algoritmos

Los algoritmos utilizados en este trabajo son:

- **Naive Bayes**

- **SVM**

## 4. Métricas de Evaluación

- AUC: es una métrica que mide la capacidad del modelo de distinguir entre clases variando el threshold de separación, es decir, la probabilidad con la que se considera la pertenencia a una clase. En la imagen inferior obtenida de [towardsdatascience.com](https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5), se muestra una separación entre las distribuciones de probabilidad de cada clase y la ROC resultante al mover el threshold.

<img src="./img_asg1/roc_sep_td.png" alt="Drawing" style="width: 450px;" align="left"/><img src="./img_asg1/roc_td.png" alt="Drawing" style="width: 210px;" align="left"/>

En este caso, las distribuciones de probabilidad son dadas por el modelo, y el threshold de separación es el que se varía para obtener la ROC y su consecuente AUC. Si el threshold se mueve, es un desplazamiento en la curva ROC. Si el threshold se mueve hacia la izquierda, se aumenta en TPR y FPR, es decir, el método detecta más fácilmente los positivos (o toma todos como positivos) pero dejando pasar muchos falsos positivos, ya que se disminuye la exigencia para ser positivo, resultando en subir en la curva ROC. Si se aumenta la exigencia para detectar reales positivos, se desplaza bajando por la ROC, teniendo menor tasa de reales positivos y por lo tanto, también de falsos positivos.

En este caso, se tiene que la AUC es 0.7, es decir, el modelo tiene un 70% de probabilidad de distinguir entre reales positivos y falsos positivos por clase. En el caso de multiclases, se realiza una heurística de uno versus todos para calcular las probabilidades.

En este caso, para el cálculo del modelo, se realiza un promedio ponderado de las AUC para las clases bajo, medio y alto. Luego, se realiza un promedio de los AUC entre las clases de sentimientos.
    
- Kappa: El coeficiente Cohen's Kappa es un estadístico de la capacidad del modelo de "estar de acuerdo" con otro anotador o clasificador, en este caso, con el anotador de los labels que consideramos reales. Para calcular el coeficiente de Kappa, se ve la matriz de confusión y se realiza un cálculo de haber clasificado correctamente solamente por coincidencia. Para ello se calcula el accuracy del modelo, es decir, la suma de la diagonal sobre la traza de la matriz de confusión, y se le resta las correctas por coincidencia. Este último, según el canal [MINT TMS Tutorials by Christian Hollmann](https://youtu.be/fOR_8gkU3UE), se calcula como la cantidad de positivos según el modelo, sobre el total de muestras, por la cantidad de positivos según nuestros labels, sobre el total de muestras; más la cantidad de negativos según el modelo sobre el total de muestras, por la cantidad de negativos según los labels sobre el total de muestras. El coeficiente de Kappa se calcula como:

$$K = \frac{0A - AC}{1 - AC}$$

Donde $0A$ es el accuracy obtenido, y $AC$ es la probabilida de haberle acertado por coincidencia. Un coeficiente de Cohen Kappa superior a 0.8 indica un buen rendimiento del modelo sobre haberle acertado por coincidencia. Mientras que un coeficiente inferior o negativo, indica un mal rendimiento del modelo.

- Accuracy: El accuracy es el coeficiente de evaluación más usado para evaluar a un modelo. Con él se calcula el nivel de acuerdo que tiene el modelo con los labels considerados reales, se calcula como la suma de la diagonal de la matriz de confusión sobre el total de las muestras consideradas en la evaluación. Mientras más cercano a 1 quire decir que el modelo se parece más a los labels considerados reales, mientras que un accuracy 0, quiere decir que el modelo no pudo predecir correctamente ninguna etiqueta.


## 5. Experimentos

...

### Importar librerías y utiles

In [1]:
import pandas as pd
import os
import numpy as np
import shutil

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import confusion_matrix, cohen_kappa_score, classification_report, accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from nltk.tokenize import TweetTokenizer
from nltk.sentiment.util import mark_negation
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import opinion_lexicon, stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer

# !pip install -U emojis
# !pip install emosent-py
# !pip install emoji --upgrade
import emoji
import emojis
from emosent import get_emoji_sentiment_rank

import gensim.downloader as api
import string

from collections import Counter

In [2]:
import nltk
# nltk.download('opinion_lexicon')
# nltk.download('vader_lexicon')
# nltk.download('stopwords')
# nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/martin/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
# negative_words = pd.read_csv('https://raw.githubusercontent.com/MartinVIllesca/CC6205-Procesamiento-de-Lenguaje-Natural/master/data_t1/opinion-lexicon-English/negative-words.csv',
#                              sep='\n', header=None, error_bad_lines=False)
# positive_words = pd.read_csv('https://raw.githubusercontent.com/MartinVIllesca/CC6205-Procesamiento-de-Lenguaje-Natural/master/data_t1/opinion-lexicon-English/positive-words.csv',
#                              sep='\n', header=None, error_bad_lines=False)

positive_words = np.hstack((list(positive_words),
                            'hugging_face',
                            'popcorn'))
negative_words = np.hstack((list(negative_words),
                            'spider',
                            'face_with_head-bandage',
                            'upside-down_face',
                            'face_with_rolling_eyes',
                            'zipper-mouth_face',
                            'slightly_frowning_face'))

In [4]:
# limpiar puntuaciones y separar por tokens.
punctuation = string.punctuation + "«»“”‘’…—"
stopwords = pd.read_csv(
    'https://raw.githubusercontent.com/Alir3z4/stop-words/master/english.txt'
).values
stopwords = Counter(stopwords.flatten().tolist())

In [5]:
# Doc2Vec Model
glove_twitter = api.load("glove-twitter-25")  # download the model and return as object ready for use
# glove_twitter.most_similar("cat")

stemmer = SnowballStemmer('english')
lemmatizer = WordNetLemmatizer() 

19638 | INFO | loading projection weights from /home/martin/gensim-data/glove-twitter-25/glove-twitter-25.gz
19638 | INFO | loaded (1193514, 25) matrix from /home/martin/gensim-data/glove-twitter-25/glove-twitter-25.gz


### Definir métodos de evaluación

Estas funciones están a cargo de evaluar los resultados de la tarea. No deberían cambiarlas.


In [6]:
def auc_score(test_set, predicted_set):
    high_predicted = np.array([prediction[2] for prediction in predicted_set])
    medium_predicted = np.array(
        [prediction[1] for prediction in predicted_set])
    low_predicted = np.array([prediction[0] for prediction in predicted_set])
    high_test = np.where(test_set == 'high', 1.0, 0.0)
    medium_test = np.where(test_set == 'medium', 1.0, 0.0)
    low_test = np.where(test_set == 'low', 1.0, 0.0)
    auc_high = roc_auc_score(high_test, high_predicted)
    auc_med = roc_auc_score(medium_test, medium_predicted)
    auc_low = roc_auc_score(low_test, low_predicted)
    auc_w = (low_test.sum() * auc_low + medium_test.sum() * auc_med +
             high_test.sum() * auc_high) / (
                 low_test.sum() + medium_test.sum() + high_test.sum())
    return auc_w


def evaluate(predicted_probabilities, y_test, labels, dataset_name):
    # Importante: al transformar los arreglos de probabilidad a clases,
    # entregar el arreglo de clases aprendido por el clasificador.
    # (que comunmente, es distinto a ['low', 'medium', 'high'])
    predicted_labels = [
        labels[np.argmax(item)] for item in predicted_probabilities
    ]
    print('Confusion Matrix for {}:\n'.format(dataset_name))
    print(
        confusion_matrix(y_test,
                         predicted_labels,
                         labels=['low', 'medium', 'high']))

#     print('\nClassification Report:\n')
#     print(
#         classification_report(y_test,
#                               predicted_labels,
#                               labels=['low', 'medium', 'high']))
    # Reorder predicted probabilities array.
    labels = labels.tolist()
    predicted_probabilities = predicted_probabilities[:, [
        labels.index('low'),
        labels.index('medium'),
        labels.index('high')
    ]]
    auc = round(auc_score(y_test, predicted_probabilities), 3)
    print("Scores:\n\nAUC: ", auc, end='\t')
    kappa = round(cohen_kappa_score(y_test, predicted_labels), 3)
    print("Kappa:", kappa, end='\t')
    accuracy = round(accuracy_score(y_test, predicted_labels), 3)
    print("Accuracy:", accuracy)
    print('------------------------------------------------------\n')
    return np.array([auc, kappa, accuracy])

### Datos

Obtener los datasets desde el github del curso

In [127]:
# Datasets de entrenamiento.
train = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/anger-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/fear-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/joy-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/train/sadness-train.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'])
}
# Datasets que deberán predecir para la competencia.
target = {
    'anger': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/anger-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'fear': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/fear-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'joy': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/joy-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE']),
    'sadness': pd.read_csv('https://raw.githubusercontent.com/dccuchile/CC6205/master/assignments/assignment_1/data/target/sadness-target.txt', sep='\t', names=['id', 'tweet', 'class', 'sentiment_intensity'], na_values=['NONE'])
}

In [128]:
# Ejemplo de algunas filas aleatorias:
train['joy'].sample(10)

id                                              tweet class  \
711  30711  god, Facebook's design has started to remind m...   joy   
329  30329  Punchline king is back! @Paedeezy 🔥🔥🔥🔥🔥🔥🔥💯💯💯 #...   joy   
830  30830  If any trump supporters and Hillary haters wan...   joy   
175  30175  There is something v satisfying about  opening...   joy   
502  30502  i'm doing laundry and watching that 70's show ...   joy   
523  30523  I might not pay for my own health insurance bu...   joy   
877  30877  @airtelindia have some issues with my broadban...   joy   
353  30353  Watch this amazing live.ly broadcast by @jared...   joy   
147  30147    @Norn_IronMaiden @forest_fr1ends It's hilarious   joy   
78   30078  #BridgetJonesBaby is the best thing I've seen ...   joy   

    sentiment_intensity  
711                 low  
329              medium  
830                 low  
175                high  
502              medium  
523              medium  
877              medium  
353              medium  
147                high  
78                 high

### Analizar los datos 

Imprimir la cantidad de tweets de cada dataset, según su intensidad de sentimiento. Noten que las clases están desbalanceadas. 

In [129]:
def get_group_dist(group_name, train):
    print(group_name, "\n",
          train[group_name].groupby('sentiment_intensity').count(),
          '\n---------------------------------------\n')
for dataset_name in train:
    get_group_dist(dataset_name, train)

anger 
                       id  tweet  class
sentiment_intensity                   
high                 163    163    163
low                  161    161    161
medium               617    617    617 
---------------------------------------

fear 
                       id  tweet  class
sentiment_intensity                   
high                 270    270    270
low                  288    288    288
medium               699    699    699 
---------------------------------------

joy 
                       id  tweet  class
sentiment_intensity                   
high                 195    195    195
low                  219    219    219
medium               488    488    488 
---------------------------------------

sadness 
                       id  tweet  class
sentiment_intensity                   
high                 197    197    197
low                  210    210    210
medium               453    453    453 
---------------------------------------



### Oversampling

In [130]:
# train_data = dict()
# for group_name in train.keys():
#     df = train[group_name]
    
#     max_size = df.groupby('sentiment_intensity').count()['class'].max()
#     lst = [df]
#     for class_index, group in df.groupby('sentiment_intensity'):
#         oversampled = group.sample(int((max_size-len(group))/2), replace=True)     
#         lst.append(oversampled)
#     frame_new = pd.concat(lst)
    
#     train_data[group_name] = frame_new
# train = train_data

In [131]:
for dataset_name in train:
    get_group_dist(dataset_name, train)

anger 
                       id  tweet  class
sentiment_intensity                   
high                 163    163    163
low                  161    161    161
medium               617    617    617 
---------------------------------------

fear 
                       id  tweet  class
sentiment_intensity                   
high                 270    270    270
low                  288    288    288
medium               699    699    699 
---------------------------------------

joy 
                       id  tweet  class
sentiment_intensity                   
high                 195    195    195
low                  219    219    219
medium               488    488    488 
---------------------------------------

sadness 
                       id  tweet  class
sentiment_intensity                   
high                 197    197    197
low                  210    210    210
medium               453    453    453 
---------------------------------------



### Custom Features 

Para crear features personalizadas implementaremos nuestros propios Transformers (estandar de scikit para crear nuevas features entre otras cosas). Para esto:

1. Creamos nuestra clase Transformer extendiendo BaseEstimator y TransformerMixin. En este ejemplo, definiremos `CharsCountTransformer` que cuenta carácteres relevantes ('!', '?', '#') en los tweets.
2. Definios una función cómo `get_relevant_chars` que opera por cada tweet y retorna un arreglo.
3. Hacemos un override de la función `transform` en donde iteramos por cada tweet, llamamos a la función que hicimos antes y agregamos sus resultados a un arrelo. Finalmente lo retornamos.

Esto nos facilitará el trabajo mas adelante. Una Guia completa de las transformaciones predefinidas en scikit pueden encontrarla [aquí](https://scikit-learn.org/stable/data_transforms.html).



In [132]:
def count_repeated_dots(tweet):
        """
        Count number of contiguous dots.
        """
        counter = 0
        prev_is_dot = False
        for c in tweet[1:]:
            if c == '.':
                if prev_is_dot:
                    counter += 1
                else:
                    prev_is_dot = True
            else:
                prev_is_dot = False
        return counter

In [133]:
class CharsCountTransformer(BaseEstimator, TransformerMixin):
    
    def get_relevant_chars(self, tweet):
        num_hashtags = tweet.count('#')
        num_exclamations = tweet.count('!')
        num_interrogations = tweet.count('?')
        num_uppercases = sum(1 for c in tweet if c.isupper())  
        num_repeated_chars = self.count_repeated_chars(tweet)
        num_repeated_dots = self.count_repeated_dots(tweet)
        
        return [num_hashtags, num_exclamations, num_interrogations,
                num_uppercases, num_repeated_chars, num_repeated_dots]
    
    def get_emojis(self, tweet):
        """
        Get number, sentiment_score, and polarity of emojis.
        """
        emojis_list = [c for c in tweet if c in emoji.UNICODE_EMOJI]
        positive, negative, neutral, sent_score, type_pos, type_neg = 0, 0, 0, 0, 0, 0
        no_pesca = 0
        for emoj in emojis_list:
            try:
                em = get_emoji_sentiment_rank(emoj)
#                 positive += em['positive']
#                 negative += em['negative']
#                 neutral += em['neutral']
                sent_score += abs(em['sentiment_score'])
                if em['sentiment_score']>0:
                    type_pos += 1
                else:
                    type_neg += 1
                    
            # if get_emoji_sentiment_rank doesn't recognize the emoji
            except:  
                emoji_name = emoji.UNICODE_EMOJI.get(emoj)[1:-1]
                if emoji_name in positive_words:
                    type_pos += 1
                    continue
                elif emoji_name in negative_words:
                    type_neg += 1
                    continue
                else:
                    # Evaluate by words
                    for idx, w in enumerate(emoji_name.split('_')):
                        if w in positive_words:
                            type_pos += 1
                            break
                        elif w in negative_words:
                            type_neg += 1
                            break
        # Igual sigue trucho, porque solo considera la informacion de si el emoji es positivo o negativo
        # pero el emoji va a tener sent_score = 0, no seria tan comparable con los emojis que 
        # sí eran compatibles y no necesitaron esta trucheria, por lo que sí tienen sent_score
        return [len(emojis_list), sent_score, type_pos, type_neg]

    def neg_transform(self, X):
        """
        Append '_NEG' to all words after a negation.
        """
        converted = []
        for tweet in X:
            neg = mark_negation(tweet.split(' '))
            sentence = ' '.join(word for word in neg)
            converted.append(sentence)
        return converted
    
    def count_repeated_chars(self, tweet):
        """
        Count number of more than twice repeated chars ( >= three times).
        """
        c_prev = tweet[0]
        counter = 0
        twice = False
        for c in tweet[1:]:
            if c==c_prev:
                if twice:
                    counter += 1
                twice = True
            else:
                twice = False
            c_prev = c
        return counter
    
    def count_repeated_dots(self, tweet):
        """
        Count number of contiguous dots.
        """
        counter = 0
        prev_is_dot = False
        for c in tweet[1:]:
            if c == '.':
                if prev_is_dot:
                    counter += 1
                else:
                    prev_is_dot = True
            else:
                prev_is_dot = False
        return counter
    
    def transform(self, X, y=None):
        chars = []
        X_neg = self.neg_transform(X)
        for tweet in X_neg:
            features = np.hstack((self.get_relevant_chars(tweet),
                                  self.get_emojis(tweet)))
            chars.append(features)
        return np.array(chars)

    def fit(self, X, y=None):
        return self

In [134]:
class LiuFeatureExtractor(BaseEstimator, TransformerMixin):
    """
    Takes in a corpus of tweets and calculates features using Bing Liu's lexicon.
    """

    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.pos_set = set(opinion_lexicon.positive())
        self.neg_set = set(opinion_lexicon.negative())

    def liu_score(self,sentence):
        """
        Calculates the number of positive and negative words in the sentence using Bing Liu's Lexicon.
        """ 
        tokenized_sent = self.tokenizer.tokenize(sentence)
        pos_words = 0
        neg_words = 0
        for word in tokenized_sent:
            if word in self.pos_set:
                pos_words += 1
            elif word in self.neg_set:
                neg_words += 1
        return [pos_words,neg_words]

    def transform(self, X, y=None):
        """
        Applies liu_score on a data.frame containing tweets.
        """
        values = []
        for tweet in X:
            values.append(self.liu_score(tweet))

        return(np.array(values))

    def fit(self, X, y=None):
        """
        This function must return `self` unless we expect the transform function to perform a 
        different action on training and testing partitions (e.g., when we calculate unigram features, 
        the dictionary is only extracted from the first batch).
        """
        return self


In [135]:
class VaderFeatureExtractor(BaseEstimator, TransformerMixin):
    """
    Takes in a corpus of tweets and calculates features using the Vader method.
    """

    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.sid = SentimentIntensityAnalyzer()


    def vader_score(self,sentence):
        """
        Calculates sentiment scores for a sentence using the Vader method.
        """
        pol_scores = self.sid.polarity_scores(sentence)
        return(list(pol_scores.values()))

    def transform(self, X, y=None):
        """
        Applies vader_score on a data.frame containing tweets.
        """
        values = []
        for tweet in X:
            values.append(self.vader_score(tweet))

        return(np.array(values))

    def fit(self, X, y=None):
        """
        Returns `self` unless something different happens in train and test.
        """
        return self

In [136]:
# Veamos que sucede si ejecutamos el transformer
# sample = train['joy'].sample(200).tweet
# sample = train['fear'].tweet
# test = pd.DataFrame(zip(sample, TwTokenizer().transform(sample)))
# print(test.loc[0][1].mean())
# test.head()

## Doc2Vec

In [137]:
stemmer.stem(':)')

':)'

In [138]:
lemmatizer.lemmatize('best', pos="a")

'best'

In [139]:
class Doc2VecTransformer(BaseEstimator, TransformerMixin):
    """ Transforma tweets a representaciones vectoriales usando algún modelo de Word Embeddings.
    """
    
    def __init__(self, model, aggregation_func, tokenizer, do_stem=False, do_lemmatize=False,
                 remove_stopwords=False):
        # extraemos los embeddings desde el objeto contenedor. ojo con esta parte.
        self.model = model.wv 
        self.tokenizer = tokenizer
        self.remove_stopwords = remove_stopwords
        self.do_stem = do_stem
        self.do_lemmatize = do_lemmatize
        
        # indicamos la función de agregación (np.min, np.max, np.mean, np.sum, ...)
        self.aggregation_func = aggregation_func

    def simple_tokenizer(self, doc, remove_stopwords=False, lower=False):
        """Tokenizador. Elimina signos de puntuación, lleva las letras a minúscula(opcional) y 
           separa el tweet por espacios.
        """
        tokens = self.tokenizer.tokenize(doc)
        final_tokens = []
        for t in tokens:
            try:
                if t[0]=='#':  # Convert hashtags
                    t = t[1:]
            except:
                print('Except', doc)
            if remove_stopwords:
                if t.lower() in stopwords:
                    continue
            final_tokens.append(t)
        
        return final_tokens
    
    def stem(self, doc):  
        doc = stemmer.stem(doc)
        return doc
    
    def lemmatize(self, doc):
        
        doc = lemmatizer.lemmatize(doc)
        return doc
        
#         if lower:
#             doc.translate(str.maketrans('', '', string.punctuation)).lower().split()
#         return doc.translate(str.maketrans('', '', string.punctuation)).split()

    def transform(self, X, y=None):
        
        doc_embeddings = []
        no_embeddings = False
        for doc in X:
            # tokenizamos el documento. Se llevan todos los tokens a minúscula. 
            # ojo con esto, ya que puede que tokens con minúscula y mayúscula tengan
            # distintas representaciones
            
            tokens = self.simple_tokenizer(doc, self.remove_stopwords) 
    
            selected_wv = []
            for token in tokens:
                token = token.lower()
                
                # Stem or lemmatize
                if self.do_stem:
                    token = self.stem(token)
                elif self.do_lemmatize:
                    token = self.lemmatize(token)
                
                if token in self.model.vocab:
                    selected_wv.append(self.model[token])
                    
            # si seleccionamos por lo menos un embedding para el tweet, lo agregamos y luego lo añadimos.
            if len(selected_wv) > 0:
                doc_embedding = self.aggregation_func(np.array(selected_wv), axis=0)
                doc_embeddings.append(doc_embedding)
            # si no, añadimos un vector de ceros que represente a ese documento.
            else: 
                if not no_embeddings:
                    print('Couldnt find any embedding for tweet:')
                    no_embeddings = True
                print(doc)
                doc_embeddings.append(np.zeros(self.model.vector_size)) # la dimension del modelo 

        return np.array(doc_embeddings)

    def fit(self, X, y=None):
        return self

### Definir la representación y el clasificador

Para esto, definiremos Pipelines. Un `Pipeline` es una lista de transformaciones y un estimador(clasificador) ubicado al final el cual define el flujo que seguiran nuestros datos dentro del sistema que creemos. Nos permite ejecutar facilmente el mismo proceso sobre todos los datasets que usemos, simplificando así nuestra programación.

El pipeline más básico que podemos hacer es transformar el dataset a Bag of Words y después usar clasificar el BoW usando NaiveBayes:

```python
    Pipeline([('bow', CountVectorizer()), ('clf', MultinomialNB())])
```


Ahora, si queremos usar nuestra transformación para agregar las features que creamos, usaremos `FeatureUnion`. Esta simplemente concatenará los vectores resultantes de ejecutar BoW y los Transformer en un solo vector.

```python
    Pipeline([('features',FeatureUnion([('bow', CountVectorizer()),
                                        ('chars_count',CharsCountTransformer())])),
              ('clf', MultinomialNB())])

```





Recuerden que cada pipeline representa un sistema de clasificación distinto. Por lo mismo, deben instanciar uno por cada problema que resuelvan. De lo contrario, podrían solapar resultados.  Para esto, les recomendamos crear los pipeline en distintas funciones, como la siguiente:

In [140]:
tfidf = TfidfVectorizer(tokenizer=TweetTokenizer().tokenize)

# doc2vec_mean = Doc2VecTransformer(glove_twitter, np.mean)
# doc2vec_sum = Doc2VecTransformer(glove_twitter, np.sum, TweetTokenizer())
doc2vec_max_remove_stop = Doc2VecTransformer(glove_twitter, np.max, TweetTokenizer(), remove_stopwords=True)
doc2vec_max = Doc2VecTransformer(glove_twitter, np.max, TweetTokenizer())
doc2vec_min_remove_stop = Doc2VecTransformer(glove_twitter, np.min, TweetTokenizer(), remove_stopwords=True)
doc2vec_min = Doc2VecTransformer(glove_twitter, np.min, TweetTokenizer())

doc2vec_max_stem = Doc2VecTransformer(glove_twitter, np.max, TweetTokenizer(), do_stem=True)
doc2vec_max_lem = Doc2VecTransformer(glove_twitter, np.max, TweetTokenizer(), do_lemmatize=True)

liu = LiuFeatureExtractor(tokenizer=TweetTokenizer())
vader = VaderFeatureExtractor(tokenizer=TweetTokenizer())

<ipython-input-139-244878b53aae>:8: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  self.model = model.wv


In [141]:
def get_experiment_0_pipeline():
    """
    CountVectorizer + CharsCountTransformer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer())
                                    ])), ('clf', MultinomialNB())])

In [142]:
def get_experiment_01_pipeline():
    """
    CountVectorizer + CharsCountTransformer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer())
                                    ])), ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [143]:
def get_experiment_1_pipeline():
    """
    CountVectorizer + TweetTokenizer + CharsCountTransformer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(tokenizer=TweetTokenizer().tokenize, 
                                                            ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer())
                                    ])), ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [144]:
def get_experiment_2_pipeline():
    """
    CountVectorizer + TweetTokenizer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(tokenizer=TweetTokenizer().tokenize,
                                                            ngram_range=(1, 3)))])),
                     ('clf', MLPClassifier(hidden_layer_sizes=(30, 20)))])

In [145]:
def get_experiment_21_pipeline():
    """
    CountVectorizer + TweetTokenizer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(tokenizer=TweetTokenizer().tokenize,
                                                            ngram_range=(1, 3)))])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [146]:
def get_experiment_22_pipeline():
    """
    CountVectorizer + TweetTokenizer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(tokenizer=TweetTokenizer().tokenize,
                                                            ngram_range=(1, 3)))])),
                     ('clf', LogisticRegression(max_iter=1000, multi_class='auto'))])

In [147]:
def get_experiment_3_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + CharsCountTransformer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf),
                                    ('chars_count', CharsCountTransformer())])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [148]:
def get_experiment_4_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + NB
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [149]:
def get_experiment_5_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + Doc2Vec (removing stopwords) + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', TfidfVectorizer(tokenizer=TweetTokenizer().tokenize)),
                                    ('doc2vec', doc2vec_max_remove_stop)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [150]:
def get_experiment_6_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + Doc2Vec (without removing stopwords) + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf),
                                    ('doc2vec', doc2vec_max)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [151]:
def get_experiment_61_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + Doc2Vec (without removing stopwords) + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf),
                                    ('doc2vecmax', doc2vec_max),
                                    ('doc2vecmin', doc2vec_min)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [152]:
def get_experiment_62_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + Doc2Vec (without removing stopwords) + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf),
                                    ('doc2vecmax_stem', doc2vec_max_stem)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [153]:
def get_experiment_63_pipeline():
    """
    TfidfVectorizer + TweetTokenizer + Doc2Vec (without removing stopwords) + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('tf-idf', tfidf),
                                    ('doc2vecmax_lem', doc2vec_max_lem)])),
                     ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [154]:
def get_experiment_7_pipeline():
    """
    CountVectorizer + CharsCountTransformer +  LiuFeatureExtractor + VaderFeatureExtractor + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer()),
                                    ('liu', liu),
                                    ('vader', vader)
                                    ])), ('clf', SVC(probability=True))])

In [155]:
def get_experiment_71_pipeline():
    """
    CountVectorizer + CharsCountTransformer +  LiuFeatureExtractor + VaderFeatureExtractor + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer()),
                                    ('liu', liu),
                                    ('vader', vader)
                                    ])), ('clf', LogisticRegression(solver='liblinear',multi_class='ovr'))])

In [156]:
def get_experiment_72_pipeline():
    """
    CountVectorizer + CharsCountTransformer +  LiuFeatureExtractor + VaderFeatureExtractor + SVM
    """
    return Pipeline([('features',
                      FeatureUnion([('bow', CountVectorizer(ngram_range=(1, 3))),
                                    ('chars_count', CharsCountTransformer()),
                                    ('liu', liu),
                                    ('vader', vader)
                                    ])), ('clf', LogisticRegression(max_iter=1000, multi_class='auto'))])

In [157]:
# al parecer, el mejor es LogisticRegression(solver='liblinear',multi_class='ovr')

### Ejecutar el pipeline para algún dataset

In [158]:
def over_sampling(X, y):
    """
    Oversamplea unos datos
    """
#     print(X)
#     print(y)
    X_over = []
    y_over = []
    
    n_max = np.max([np.sum([y == c]) for c in np.unique(y)])
    print([np.sum([y == c]) for c in np.unique(y)])
    
    for c in np.unique(y):
        n = n_max - np.sum([y == c])
        if n == 0: continue
        indices = np.where(y == c)[0]
        arr_sampling = np.random.randint(low=0,
                                         high=len(indices),
                                         size=int(n / 2))
        indices = np.array(indices[arr_sampling])
        
        X_over = np.concatenate([X_over, [X.iloc[i] for i in indices]])
        y_over = np.concatenate([y_over, [y.iloc[i] for i in indices]])
    
    X_over = np.concatenate([X, X_over])
    y_over = np.concatenate([y, y_over])
    
    
    print([np.sum([y_over == c]) for c in np.unique(y)])
    
    return X_over, y_over

In [163]:
def run(dataset, dataset_name, pipeline):
    """Creamos el pipeline y luego lo ejecutamos el pipeline sobre un dataset. 
    Retorna el modelo ya entrenado mas sus labels asociadas y los scores obtenidos al evaluarlo."""

    # Dividimos el dataset en train y test.
    X_train, X_test, y_train, y_test = train_test_split(
        dataset.tweet,
        dataset.sentiment_intensity,
        shuffle=True,
        test_size=0.33)
#     print(type(X_train))
    
    X_train, y_train = over_sampling(X_train, y_train)
    
    # Entrenamos el clasificador (Ejecuta el entrenamiento sobre todo el pipeline)
    pipeline.fit(X_train, y_train)

    # Predecimos las probabilidades de intensidad de cada elemento del set de prueba.
    predicted_probabilities = pipeline.predict_proba(X_test)

    # Obtenemos el orden de las clases aprendidas.
    learned_labels = pipeline.classes_

    # Evaluamos:
    scores = evaluate(predicted_probabilities, y_test, learned_labels, dataset_name)
    return pipeline, learned_labels, scores

### Ejecutar el sistema creado por cada train set

Este código crea y entrena los 4 sistemas de clasificación y luego los evalua. Para los experimentos, pueden copiar este código variando el pipeline cuantas veces estimen conveniente.

In [164]:
def run_experiments(experiments):
    for n, pipeline in enumerate(experiments):
        classifiers = []
        learned_labels_array = []
        scores_array = []

        # Por cada nombre_dataset, dataset en train ('anger', 'fear', 'joy', 'sadness')
        for dataset_name, dataset in train.items():

            # ejecutamos el pipeline sobre el dataset
            classifier, learned_labels, scores = run(dataset, dataset_name, pipeline)

            # guardamos el clasificador entrenado (en realidad es el pipeline ya entrenado...)
            classifiers.append(classifier)

            # guardamos las labels aprendidas por el clasificador
            learned_labels_array.append(learned_labels)

            # guardamos los scores obtenidos
            scores_array.append(scores)

        # print avg scores
        print('Experiment', n,
          "Average scores:\n\n",
          "Average AUC: {0:.3g}\t Average Kappa: {1:.3g}\t Average Accuracy: {2:.3g}"
          .format(*np.array(scores_array).mean(axis=0)))

In [165]:
# experiments = [get_experiment_01_pipeline(),
#                get_experiment_1_pipeline(),
#                get_experiment_2_pipeline(),
#                get_experiment_3_pipeline(),
#                get_experiment_4_pipeline(),
#                get_experiment_6_pipeline(),
#                get_experiment_71_pipeline()]
experiments = [get_experiment_6_pipeline(),
               get_experiment_62_pipeline(),
               get_experiment_63_pipeline()]

# experiments = [get_experiment_6_pipeline()]

run_experiments(experiments)

[114, 102, 414]
[264, 258, 414]
Confusion Matrix for anger:

[[ 17  38   4]
 [ 21 160  22]
 [  2  30  17]]
Scores:

AUC:  0.651	Kappa: 0.208	Accuracy: 0.624
------------------------------------------------------

[182, 203, 457]
[319, 330, 457]
Confusion Matrix for fear:

[[ 37  39   9]
 [ 42 161  39]
 [  9  42  37]]
Scores:

AUC:  0.662	Kappa: 0.243	Accuracy: 0.566
------------------------------------------------------

[123, 139, 342]
[232, 240, 342]
Confusion Matrix for joy:

[[32 35 13]
 [21 98 27]
 [ 2 30 40]]
Scores:

AUC:  0.762	Kappa: 0.305	Accuracy: 0.57
------------------------------------------------------

[133, 149, 294]
[213, 221, 294]
Confusion Matrix for sadness:

[[ 24  29   8]
 [ 33 110  16]
 [  4  30  30]]
Scores:

AUC:  0.673	Kappa: 0.269	Accuracy: 0.577
------------------------------------------------------

Experiment 0 Average scores:

 Average AUC: 0.687	 Average Kappa: 0.256	 Average Accuracy: 0.584
[110, 108, 412]
[261, 260, 412]
Confusion Matrix for anger:

[

In [167]:
pipeline = get_experiment_0_pipeline()

classifiers = []
learned_labels_array = []
scores_array = []

# Por cada nombre_dataset, dataset en train ('anger', 'fear', 'joy', 'sadness')
for dataset_name, dataset in train.items():

    # ejecutamos el pipeline sobre el dataset
    classifier, learned_labels, scores = run(dataset, dataset_name, pipeline)

    # guardamos el clasificador entrenado (en realidad es el pipeline ya entrenado...)
    classifiers.append(classifier)

    # guardamos las labels aprendidas por el clasificador
    learned_labels_array.append(learned_labels)

    # guardamos los scores obtenidos
    scores_array.append(scores)

# print avg scores
print("Average scores:\n\n",
  "Average AUC: {0:.3g}\t Average Kappa: {1:.3g}\t Average Accuracy: {2:.3g}"
  .format(*np.array(scores_array).mean(axis=0)))

[111, 100, 419]
[265, 259, 419]
Confusion Matrix for anger:

[[  9  49   3]
 [ 14 166  18]
 [  1  34  17]]
Scores:

AUC:  0.58	Kappa: 0.158	Accuracy: 0.617
------------------------------------------------------

[182, 199, 461]
[321, 330, 461]
Confusion Matrix for fear:

[[ 30  51   8]
 [ 23 182  33]
 [  2  62  24]]
Scores:

AUC:  0.612	Kappa: 0.187	Accuracy: 0.569
------------------------------------------------------

[135, 142, 327]
[231, 234, 327]
Confusion Matrix for joy:

[[42 34  1]
 [44 96 21]
 [ 3 27 30]]
Scores:

AUC:  0.715	Kappa: 0.277	Accuracy: 0.564
------------------------------------------------------

[128, 142, 306]
[217, 224, 306]
Confusion Matrix for sadness:

[[ 14  52   2]
 [ 12 127   8]
 [  5  42  22]]
Scores:

AUC:  0.637	Kappa: 0.216	Accuracy: 0.574
------------------------------------------------------

Average scores:

 Average AUC: 0.636	 Average Kappa: 0.209	 Average Accuracy: 0.581


### Predecir los target set y crear la submission

Aquí predecimos los target set usando los clasificadores creados y creamos los archivos de las submissions.

In [ ]:
def predict_target(dataset, classifier, labels):
    # Predecir las probabilidades de intensidad de cada elemento del target set.
    predicted = pd.DataFrame(classifier.predict_proba(dataset.tweet), columns=labels)
    # Agregar ids
    predicted['id'] = dataset.id.values
    # Reordenar las columnas
    predicted = predicted[['id', 'low', 'medium', 'high']]
    return predicted

In [ ]:
predicted_target = {}

# Crear carpeta ./predictions
if (not os.path.exists('./predictions')):
    os.mkdir('./predictions')

else:
    # Eliminar predicciones anteriores:
    shutil.rmtree('./predictions')
    os.mkdir('./predictions')

# por cada target set:
for idx, key in enumerate(target):
    # Predecirlo
    print(classifiers[idx])
    predicted_target[key] = predict_target(target[key], classifiers[idx],
                                           learned_labels_array[idx])
    # Guardar predicciones en archivos separados. 
    predicted_target[key].to_csv('./predictions/{}-pred.txt'.format(key),
                                 sep='\t',
                                 header=False,
                                 index=False)

# Crear archivo zip
a = shutil.make_archive('predictions', 'zip', './predictions')

## 6. Conclusiones

...