<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#📚-Objetivos-de-la-clase-📚" data-toc-modified-id="📚-Objetivos-de-la-clase-📚-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>📚 Objetivos de la clase 📚</a></span></li><li><span><a href="#Motivación" data-toc-modified-id="Motivación-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Motivación</a></span><ul class="toc-item"><li><span><a href="#El-gran-problema-de-Bag-of-Words" data-toc-modified-id="El-gran-problema-de-Bag-of-Words-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>El gran problema de Bag of Words</a></span></li><li><span><a href="#Hipótesis-Distribucional" data-toc-modified-id="Hipótesis-Distribucional-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Hipótesis Distribucional</a></span></li><li><span><a href="#Word-Context-Matrices" data-toc-modified-id="Word-Context-Matrices-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Word-Context Matrices</a></span></li><li><span><a href="#Word-Embeddings" data-toc-modified-id="Word-Embeddings-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Word Embeddings</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Word2vec-y-Skip-gram" data-toc-modified-id="Word2vec-y-Skip-gram-2.4.0.1"><span class="toc-item-num">2.4.0.1&nbsp;&nbsp;</span>Word2vec y Skip-gram</a></span></li></ul></li><li><span><a href="#Detalles-del-Modelo" data-toc-modified-id="Detalles-del-Modelo-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>Detalles del Modelo</a></span></li></ul></li><li><span><a href="#La-capa-Oculta-y-los-Embeddings" data-toc-modified-id="La-capa-Oculta-y-los-Embeddings-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>La capa Oculta y los Embeddings</a></span></li><li><span><a href="#Fuentes" data-toc-modified-id="Fuentes-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Fuentes</a></span></li></ul></li><li><span><a href="#Entrenar-nuestros-Embeddings" data-toc-modified-id="Entrenar-nuestros-Embeddings-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Entrenar nuestros Embeddings</a></span><ul class="toc-item"><li><span><a href="#Cargar-el-dataset-y-limpiar" data-toc-modified-id="Cargar-el-dataset-y-limpiar-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Cargar el dataset y limpiar</a></span></li><li><span><a href="#Extracción-de-Frases" data-toc-modified-id="Extracción-de-Frases-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Extracción de Frases</a></span></li><li><span><a href="#Definir-el-modelo" data-toc-modified-id="Definir-el-modelo-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Definir el modelo</a></span></li><li><span><a href="#Construir-el-vocabulario" data-toc-modified-id="Construir-el-vocabulario-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Construir el vocabulario</a></span></li><li><span><a href="#Entrenar-el-Modelo" data-toc-modified-id="Entrenar-el-Modelo-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Entrenar el Modelo</a></span></li><li><span><a href="#Guardar-y-cargar-el-modelo" data-toc-modified-id="Guardar-y-cargar-el-modelo-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Guardar y cargar el modelo</a></span></li></ul></li><li><span><a href="#Tasks:-Palabras-mas-similares-y-Analogías" data-toc-modified-id="Tasks:-Palabras-mas-similares-y-Analogías-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Tasks: Palabras mas similares y Analogías</a></span><ul class="toc-item"><li><span><a href="#Palabras-mas-similares" data-toc-modified-id="Palabras-mas-similares-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Palabras mas similares</a></span></li><li><span><a href="#Analogías" data-toc-modified-id="Analogías-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Analogías</a></span></li><li><span><a href="#Visualizar" data-toc-modified-id="Visualizar-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Visualizar</a></span></li></ul></li><li><span><a href="#Word-Embeddings-como-características-para-clasificar" data-toc-modified-id="Word-Embeddings-como-características-para-clasificar-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Word Embeddings como características para clasificar</a></span><ul class="toc-item"><li><span><a href="#Cargar-el-dataset" data-toc-modified-id="Cargar-el-dataset-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Cargar el dataset</a></span></li><li><span><a href="#Dividir-el-dataset-en-training-y-test" data-toc-modified-id="Dividir-el-dataset-en-training-y-test-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Dividir el dataset en training y test</a></span></li><li><span><a href="#Doc2vec" data-toc-modified-id="Doc2vec-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Doc2vec</a></span></li><li><span><a href="#Definimos-el-pipeline" data-toc-modified-id="Definimos-el-pipeline-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Definimos el pipeline</a></span></li></ul></li><li><span><a href="#Usandolo-con-BoW" data-toc-modified-id="Usandolo-con-BoW-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Usandolo con BoW</a></span><ul class="toc-item"><li><span><a href="#Bias-en-Embeddings" data-toc-modified-id="Bias-en-Embeddings-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Bias en Embeddings</a></span></li><li><span><a href="#Propuesto..." data-toc-modified-id="Propuesto...-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Propuesto...</a></span></li></ul></li></ul></div>

# Auxiliar 2 - Word Embeddings


## 📚 Objetivos de la clase 📚

La clase auxiliar de esta semana tendrá varios objetivos: 

- Motivación y repaso de qué son los Word Embeddings. 
- Entrenar nuestros propios `word embeddings` usando el dataset de noticias de la radio biobio. 
- Experimentar y visualizar los embeddings entrenados. 
- Por último, resolver la misma tarea de la clase auxiliar 1, pero ahora usando los embeddings que hemos calculado. 


Para desarrollar ustedes mismos el auxiliar, necesitarán los siguientes paquetes: 

- `pandas`
- `numpy`
- `gensim`
- `plotly`
- `sklearn`
- `wefe`

Una vez resuelto, pueden utilizar cualquier parte del código que les parezca prudente para la tarea 1 (que también es de clasificación de texto! 😊).


El notebook del auxiliar ya ejecutado se encuentra en el [github](https://github.com/dccuchile/CC6205/tree/master/tutorials) del curso (Recuerden dejar su Star ⭐😉!).

## Motivación

### El gran problema de Bag of Words

Pensemos en estas 3 frases como documentos:

- $doc_1$: `¡Buenísima la marraqueta!`
- $doc_2$: `¡Estuvo espectacular ese pan francés!`
- $doc_3$: `!Buenísima esa pintura!`

Sabemos $doc_1$ y $doc_2$ hablan de lo mismo 🍞🍞👌 y que $doc_3$ 🎨 no tiene mucho que ver con los otros.

Supongamos que queremos ver que tan similares son ambos documentos. 
Para esto, generamos un modelo `Bag of Words` sobre el documento. Es decir, transformamos cada palabra a un vector one-hot y luego los sumamos por documento. Además, omitimos algunas stopwords y consideramos pan frances como un solo token.

$$v = \{buenísima, marraqueta, estuvo, espectacular, pan\ francés, pintura\}$$

Entonces, el $\vec{doc_1}$ quedará:

$$\begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0\\ 0\end{bmatrix} + 
  \begin{bmatrix}0 \\ 1 \\ 0 \\ 0 \\ 0\\ 0\end{bmatrix} =
  \begin{bmatrix}1 \\ 1 \\ 0 \\ 0 \\ 0\\ 0\end{bmatrix}$$

El $\vec{doc_2}$ quedará:

$$\begin{bmatrix}0 \\ 0 \\ 1 \\ 0 \\ 0\\ 0\end{bmatrix} + 
  \begin{bmatrix}0 \\ 0 \\ 0 \\ 1 \\ 0\\ 0\end{bmatrix} + 
  \begin{bmatrix}0 \\ 0 \\ 0 \\ 0 \\ 1\\ 0\end{bmatrix} = 
  \begin{bmatrix}0 \\ 0 \\ 1 \\ 1 \\ 1\\ 0\end{bmatrix}$$

Y el $\vec{doc_3}$: 

$$\begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0\\ 0\end{bmatrix} + 
  \begin{bmatrix}0 \\ 0 \\ 0 \\ 0 \\ 0\\ 1\end{bmatrix} =
  \begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0\\ 1\end{bmatrix}$$



**¿Cuál es el problema?**

`buenísima` $\begin{bmatrix}1 \\ 0 \\ 0 \\ 0 \\ 0 \\0\end{bmatrix}$ y `espectacular` $ \begin{bmatrix}0 \\ 0 \\ 0 \\ 1 \\ 0 \\ 0\end{bmatrix}$ representan ideas muy similares. Por otra parte, sabemos que `marraqueta` $\begin{bmatrix}0 \\ 1 \\ 0 \\ 0 \\ 0 \\0\end{bmatrix}$ y `pan francés` $\begin{bmatrix}0 \\ 0 \\ 0 \\ 0 \\ 1 \\0\end{bmatrix}$ se refieren al mismo objeto. Pero en este modelo, estos **son totalmente distintos**. Es decir, los vectores de las palabras que `buenísima` y `espectacular` son tan distintas como `marraqueta` y `pan francés`. Esto evidentemente, repercute en la calidad de los modelos que creamos a partir de nuestro Bag of Words.

Ahora, si queremos ver que documento es mas similar a otro usando distancia euclidiana, veremos que:

$$d(doc_1, doc_2) = 2.236$$
$$d(doc_1, doc_3) = 1.414$$

Es decir, $doc_1$ se parece mas a $doc_3$ aunque nosotros sabemos que $doc_1$ y $doc_2$ nos están diciendo lo mismo!


Nos gustaría que eso no sucediera. Que existiera algún método que nos permitiera hacer que palabras similares tengan representaciones similares. Y que con estas, representemos mejor a los documentos.


--------------------

### Hipótesis Distribucional

Estamos buscando algún enfoque que nos permita representar las palabras de forma no aislada, si no como algo que además capture el significado de esta.

Pensemos un poco en la **hipótesis distribucional**. Esta plantea que:

    "Palabras que ocurren en contextos iguales tienden a tener significados similares." 

O equivalentemente,

    "Una palabra es caracterizada por la compañía que esta lleva."

Esto nos puede hacer pensar que podríamos usar los contextos de las palabras para generar vectores que describan mejor dichas palabras: en otras palabras, los `Distributional Vectors`.

--------------------


### Word-Context Matrices

Es una matriz donde cada celda $(i,j)$ representa la co-ocurrencia entre una palabra objetivo/centro $w_i$ y un contexto $c_j$. El contexto son las palabras dentro de ventana de tamaño $k$ que rodean la palabra central. 

Cada fila representa a una palabra a través de su contexto. Como pueden ver, ya no es un vector one-hot, si no que ahora contiene mayor información.

El tamaño de la matriz es el tamaño del vocabulario $V$ al cuadrado. Es decir $|V|*|V|$.

<img src="https://raw.githubusercontent.com/dccuchile/CC6205/master/slides/pics/distributionalSocher.png" alt="Word-context matrices" style="width: 400px;"/>


**Problema: Creada a partir de un corpus respetable, es gigantezca**. 

Por ejemplo, para $|v| = 100.000$, la matriz tendrá $\frac{100000 * 100000 * 4}{10^9} = 40gb $.

- Es caro mantenerla en memoria 
- Los clasificadores no funcionan tan bien con tantas dimensiones (ver [maldición de la dimensionalidad](https://es.wikipedia.org/wiki/Maldici%C3%B3n_de_la_dimensi%C3%B3n)).

¿Habrá una mejor solución?

---------------------

### Word Embeddings


La idea principal de los Word Embeddings es crear representaciones vectoriales densas y de baja dimensionalidad $(d << |V|)$ de las palabras a partir de su contexto.  Para esto, se usan distintos modelos que emplean redes neuronales *shallow* o poco profundas.

Volvamos a nuestro ejemplo anterior: `buenísima` y `espectacular` ocurren muchas veces en el mismo contexto, por lo que los embeddings que los representan debiesen ser muy similares... (*ejemplos de mentira hechos a mano*):

`buenísima` $\begin{bmatrix}0.32 \\ 0.44 \\ 0.92 \\ .001 \end{bmatrix}$ y `espectacular` $\begin{bmatrix}0.30 \\ 0.50 \\ 0.92 \\ .002 \end{bmatrix}$ versus `marraqueta`  $\begin{bmatrix}0.77 \\ 0.99 \\ 0.004 \\ .1 \end{bmatrix}$ el cuál es claramente distinto.


Pero, **¿Cómo capturamos el contexto dentro de nuestros vectores?**

- Dependerá del modelo que utilizemos.


##### Word2vec y Skip-gram

Word2Vec es probablemente el paquete de software mas famoso para crear word embeddings. Este nos provee herramientas para crear distintos tipos de modelos, tales como `Skip-Gram` y `Continuous Bag of Word (CBOW)`. En este caso, solo veremos `Skip-Gram`.

**Skip-gram** es una task auxiliar con la que crearemos nuestros embeddings. Esta consiste en que por cada palabra del dataset, predigamos las palabras de su contexto (las palabras presentes en ventana de algún tamaño $k$).

Para resolverla, usaremos una red de una sola capa oculta. Los pesos ya entrenados de esta capa serán los que usaremos como embeddings.

#### Detalles del Modelo

- Como dijimos, el modelo será una red de una sola capa. La capa oculta tendrá una dimensión $d$ la cual nosotros determinaremos. Esta capa no tendrá función de activación. Sin embargo, la de salida si, la cual será una softmax.

- El vector de entrada, de tamaño $|V|$, será un vector one-hot de la palabra que estemos viendo en ese momento.

- La salida, también de tamaño $|V|$, será un vector que contenga la distribución de probabilidad de que cada palabra del vocabulario pertenezca al contexto de la palabra de entrada.

- Al entrenar, se comparará la distribución de los contextos con la suma de los vectores one-hot del contexto real.

<img src="http://mccormickml.com/assets/word2vec/skip_gram_net_arch.png" alt="Skip Gram" style="width: 600px;"/>

Nota: Esto es computacionalmente una locura. Por cada palabra de entrada, debemos calcular la probabilidad de aparición de todas las otras. Imaginen el caso de un vocabulario de 100.000 de palabras y de 10000000 oraciones...

La solución a esto es modificar la task a *Negative Sampling*. Esta transforma este problema de $|V|$ clases a uno binario. Sin embargo, no lo veremos por el tiempo, pero están muy bien explicado en el [video de la cátedra](https://www.youtube.com/watch?v=XDxzQ7JU95U&feature=youtu.be).


### La capa Oculta y los Embeddings

Al terminar el entrenamiento, ¿Qué nos queda en la capa oculta?

Una matriz de $v$ filas por $d$ columnas, la cual contiene lo que buscabamos: Una representación continua de todas las palabras de nuestro vocabualrio.  

**Cada fila de la matriz es un vector que contiene la representación continua una palabra del vocabulario.**


<img src="http://mccormickml.com/assets/word2vec/word2vec_weight_matrix_lookup_table.png" alt="Capa Oculta 1" style="width: 400px;"/>

¿Cómo la usamos eficientemente?

Simple: usamos los mismos vectores one-hot de la entrada y las multiplicamos por la matriz:

<img src="http://mccormickml.com/assets/word2vec/matrix_mult_w_one_hot.png" alt="Skip Gram" style="width: 400px;"/>



### Fuentes

Word2vec:
- mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/
- https://towardsdatascience.com/introduction-to-word-embedding-and-word2vec-652d0c2060fa

Gensim: 
- https://www.kaggle.com/pierremegret/gensim-word2vec-tutorial

Nota: Las últimas 3 imagenes pertenecen a [Chris McCormick](http://mccormickml.com/about/)


## Entrenar nuestros Embeddings

Para entrenar nuestros embeddings, usaremos el paquete gensim. Este trae una muy buena implementación de `word2vec`.




In [3]:
import re  
import pandas as pd 
from time import time  
from collections import defaultdict 
import string 
import multiprocessing
import os
import requests

# word2vec
from gensim.models import Word2Vec, KeyedVectors
from gensim.models.phrases import Phrases, Phraser

import logging  # Setting up the loggings to monitor gensim
logging.basicConfig(format="%(levelname)s - %(asctime)s: %(message)s", datefmt= '%H:%M:%S', level=logging.INFO)

# scikit-learn
from sklearn.manifold import TSNE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import CountVectorizer  
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.decomposition import PCA
from sklearn.base import BaseEstimator, TransformerMixin

# visualizaciones
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from ipywidgets import widgets

### Cargar el dataset y limpiar

Nota: Pandas descomprime por si mismo el archivo bz2. Pueden descomprimirlo manualmente usando 7zip.

In [4]:
# descargamos el dataset completo (~40mb)
dataset = pd.read_json(
    'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_clean.bz2',
    encoding="utf-8")

dataset_r = dataset.copy(deep = True)

In [5]:
# unir titulo con contenido de la noticia
content = dataset['title'] + dataset['content']

In [6]:
content.shape

(26413,)

In [7]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [8]:
from collections import Counter

# limpiar puntuaciones y separar por tokens.
punctuation = string.punctuation + "«»“”‘’…—"
stopwords = pd.read_csv(
    'https://raw.githubusercontent.com/Alir3z4/stop-words/master/spanish.txt'
).values
stopwords = Counter(stopwords.flatten().tolist())


def simple_tokenizer(doc, lower=False):
    if lower:
        tokenized_doc = doc.translate(str.maketrans(
            '', '', punctuation)).lower().split()

    tokenized_doc = doc.translate(str.maketrans('', '', punctuation)).split()

    tokenized_doc = [
        token for token in tokenized_doc if token.lower() not in stopwords
    ]
    return tokenized_doc


print(punctuation)
cleaned_content = [simple_tokenizer(doc) for doc in content.values]

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~«»“”‘’…—


In [9]:
print("Ejemplo de alguna noticia: {}".format(cleaned_content[14]))

Ejemplo de alguna noticia: ['Ministra', 'Cubillos', 'extensión', 'paro', 'docente', 'problema', 'propuesta', 'ministra', 'Educación', 'Marcela', 'Cubillos', 'refirió', 'a', 'votación', 'realizada', 'interior', 'Colegio', 'Profesores', 'decidió', 'mantener', 'paro', 'pese', 'llamado', 'presidente', 'gremio', 'Mario', 'Aguilar', 'a', 'replegarse', 'entrevista', 'programa', 'Expreso', 'Bío', 'Bío', 'Radio', 'ministra', 'valoró', 'dichos', 'Aguilar', 'previo', 'a', 'votación', 'asegurando', 'efecto', 'positivo', 'respecto', 'vuelta', 'clases', 'Paro', 'profesores', 'extiende', 'semana', '255', 'votos', 'marcaron', 'diferencia', 'sufragio', 'según', 'dijo', '95', 'colegios', 'funcionan', 'normalidad', 'ayer', 'bajaron', '490', 'colegios', 'quedaban', 'paro', 'Respecto', 'a', 'si', 'Ministerio', 'seguirá', 'negociando', 'ofrecerá', 'considerando', 'mayoría', 'votó', 'extender', 'movilización', 'ministra', 'limitó', 'a', 'decir', 'esperarán', 'resuelva', 'diálogos', 'internos', 'llevando', 'a

### Extracción de Frases

Para crear buenas representaciones, es necesario tambien encontrar conjuntos de palabras que por si solas no tengan mayor significado (como `nueva` y `york`), pero que juntas que representen ideas concretas (`nueva york`). 

Para esto, usaremos el primer conjunto de herramientas de `gensim`: `Phrases` y `Phraser`.

In [10]:
#La condición para que sean considerados es que aparezcan por lo menos 100 veces repetidas.

phrases = Phrases(cleaned_content, min_count=100, progress_per=5000) 

INFO - 23:12:39: collecting all words and their counts
INFO - 23:12:39: PROGRESS: at sentence #0, processed 0 words and 0 word types
INFO - 23:12:41: PROGRESS: at sentence #5000, processed 1239242 words and 878154 word types
INFO - 23:12:42: PROGRESS: at sentence #10000, processed 2191881 words and 1395575 word types
INFO - 23:12:44: PROGRESS: at sentence #15000, processed 3213105 words and 1891772 word types
INFO - 23:12:46: PROGRESS: at sentence #20000, processed 4342156 words and 2517165 word types
INFO - 23:12:48: PROGRESS: at sentence #25000, processed 5465003 words and 3095045 word types
INFO - 23:12:49: collected 3264063 word types from a corpus of 5796971 words (unigram + bigrams) and 26413 sentences
INFO - 23:12:49: using 3264063 counts as vocab in Phrases<0 vocab, min_count=100, threshold=10.0, max_vocab_size=40000000>


In [11]:
phrases.vocab

defaultdict(int,
            {b'Colapsa': 1,
             b'segmento': 125,
             b'Colapsa_segmento': 1,
             b'casa': 3376,
             b'segmento_casa': 1,
             b'derrumb\xc3\xb3': 76,
             b'casa_derrumb\xc3\xb3': 5,
             b'Valpara\xc3\xadso': 1986,
             b'derrumb\xc3\xb3_Valpara\xc3\xadso': 4,
             b'Noticia': 11,
             b'Valpara\xc3\xadso_Noticia': 1,
             b'Desarrollo': 833,
             b'Noticia_Desarrollo': 1,
             b'recopilando': 13,
             b'Desarrollo_recopilando': 1,
             b'antecedentes': 2185,
             b'recopilando_antecedentes': 4,
             b'noticia': 637,
             b'antecedentes_noticia': 1,
             b'qu\xc3\xa9date': 5,
             b'noticia_qu\xc3\xa9date': 1,
             b'atento': 63,
             b'qu\xc3\xa9date_atento': 1,
             b'a': 233657,
             b'atento_a': 40,
             b'actualizaciones': 19,
             b'a_actualizaciones': 

Ahora, usamos `Phraser` para re-tokenizamos el corpus con los bigramas encontrados. Es decir, juntamos los tokens separados que detectamos como frases.

In [12]:
bigram = Phraser(phrases)
sentences = bigram[cleaned_content]

INFO - 23:13:11: source_vocab length 3264063
INFO - 23:13:35: Phraser built with 1054 phrasegrams


In [13]:
# para ver como quedan las noticias retokenizadas, quitar comentario a la siguiente linea:
print(sentences[110])

['Ministro', 'Vivienda', 'enfrenta', 'polémica', 'casitas', 'calle', 'oficina', 'ministro', 'Vivienda_Urbanismo', 'Cristian', 'Monckeberg', 'refirió', 'a', 'polémica', 'reflexión', 'integración', 'social', 'déficit', 'habitacional', 'país', 'Comisión', 'Vivienda_Urbanismo', 'Senado', 'señaló', 'gran', 'mayoría', 'propietarios', 'patrimonio', 'casita', 'dos', 'departamentos', 'ahí', 'radica', 'patrimonio', 'chilenos', 'Tras', 'episodio', 'entrevista', 'programa', 'Podría_Ser', 'Peor', 'Julio', 'César', 'Rodríguez', 'remarcó', 'dichos', 'parte', 'intervención', 'larga', 'pasado', '14', 'agosto', 'siquiera', 'sacaron', 'contexto', 'escucha', 'grabación', 'efectivamente', 'suena', 'horrorosa', 'explicación', 'larga', 'tema', 'tratando', 'Senado', 'hecho', 'a', 'ningún', 'senador', 'llamó_atención', 'aseguró', 'Ministro', 'Vivienda', 'gran', 'mayoría', 'propietarios', 'casita', 'dos', 'departamentos', 'paso', 'explicó', 'instancia', 'analizando', 'hecho', 'chilenos', 'culturalmente', 'propi

### Definir el modelo



Primero, como es usual, creamos el modelo. En este caso, usaremos uno de los primero modelos de embeddings neuronales: `word2vec`

Algunos parámetros importantes:

- `min_count`: Ignora todas las palabras que tengan frecuencia menor a la indicada.
- `window` : Tamaño de la ventana. Usaremos 4.
- `size` : El tamaño de los embeddings que crearemos. Por lo general, el rendimiento sube cuando se usan mas dimensiones, pero después de 300 ya no se nota cambio. Ahora, usaremos solo 200.
- `workers`: Cantidad de CPU que serán utilizadas en el entrenamiento.

In [14]:
biobio_w2v = Word2Vec(min_count=10,
                      window=4,
                      size=200,
                      sample=6e-5,
                      alpha=0.03,
                      min_alpha=0.0007,
                      negative=20,
                      workers=multiprocessing.cpu_count())

### Construir el vocabulario

Para esto, se creará un conjunto que contendrá (una sola vez) todas aquellas palabras que aparecen mas de `min_count` veces. 

In [15]:
biobio_w2v.build_vocab(sentences, progress_per=10000)

INFO - 23:13:54: collecting all words and their counts
INFO - 23:13:54: PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
INFO - 23:13:58: PROGRESS: at sentence #10000, processed 2090563 words, keeping 99620 word types
INFO - 23:14:02: PROGRESS: at sentence #20000, processed 4142515 words, keeping 151977 word types
INFO - 23:14:05: collected 186290 word types from a corpus of 5536916 raw words and 26413 sentences
INFO - 23:14:05: Loading a fresh vocabulary
INFO - 23:14:06: effective_min_count=10 retains 38094 unique words (20% of original 186290, drops 148196)
INFO - 23:14:06: effective_min_count=10 leaves 5202906 word corpus (93% of original 5536916, drops 334010)
INFO - 23:14:06: deleting the raw counts dictionary of 186290 items
INFO - 23:14:06: sample=6e-05 downsamples 1099 most-common words
INFO - 23:14:06: downsampling leaves estimated 4050149 word corpus (77.8% of prior 5202906)
INFO - 23:14:06: estimated required memory for 38094 words and 200 dimensions: 799974

### Entrenar el Modelo

A continuación, entenaremos el modelo. 
Los parámetros que usaremos serán: 

- `total_examples`: Número de documentos.
- `epochs`: Número de veces que se iterará sobre el corpus.

Es recomendable que tengan instalado `cpython` antes de continuar. Aumenta bastante la velocidad de entrenamiento.


In [16]:
t = time()
biobio_w2v.train(sentences, total_examples=biobio_w2v.corpus_count, epochs=15, report_delay=10)
print('Time to train the model: {} mins'.format(round((time() - t) / 60, 2)))

INFO - 23:14:38: training model with 8 workers on 38094 vocabulary and 200 features, using sg=0 hs=0 sample=6e-05 negative=20 window=4
INFO - 23:14:39: EPOCH 1 - PROGRESS: at 3.98% examples, 177373 words/s, in_qsize 1, out_qsize 1
INFO - 23:14:49: EPOCH 1 - PROGRESS: at 56.35% examples, 202135 words/s, in_qsize 1, out_qsize 0
INFO - 23:14:58: worker thread finished; awaiting finish of 7 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 6 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 5 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 4 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 3 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 2 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 1 more threads
INFO - 23:14:58: worker thread finished; awaiting finish of 0 more threads
INFO - 23:14:58: EPOCH - 1 : training on 5536916 raw words (4050798 effe

INFO - 23:18:28: worker thread finished; awaiting finish of 1 more threads
INFO - 23:18:28: worker thread finished; awaiting finish of 0 more threads
INFO - 23:18:28: EPOCH - 8 : training on 5536916 raw words (4049903 effective words) took 34.0s, 118959 effective words/s
INFO - 23:18:29: EPOCH 9 - PROGRESS: at 2.49% examples, 108346 words/s, in_qsize 0, out_qsize 0
INFO - 23:18:39: EPOCH 9 - PROGRESS: at 36.85% examples, 135649 words/s, in_qsize 0, out_qsize 0
INFO - 23:18:50: EPOCH 9 - PROGRESS: at 76.07% examples, 144594 words/s, in_qsize 0, out_qsize 0
INFO - 23:18:58: worker thread finished; awaiting finish of 7 more threads
INFO - 23:18:58: worker thread finished; awaiting finish of 6 more threads
INFO - 23:18:58: worker thread finished; awaiting finish of 5 more threads
INFO - 23:18:58: worker thread finished; awaiting finish of 4 more threads
INFO - 23:18:58: worker thread finished; awaiting finish of 3 more threads
INFO - 23:18:58: worker thread finished; awaiting finish of 2 m

Time to train the model: 7.01 mins


Ahora que terminamos de entrenar el modelo, le indicamos que no lo entrenaremos mas. 
Esto nos permitirá ejecutar eficientemente las tareas que realizaremos.

In [17]:
biobio_w2v.init_sims(replace=True)

INFO - 23:25:07: precomputing L2-norms of word weight vectors


###  Guardar y cargar el modelo

Para ahorrar tiempo, usaremos un modelo preentrenado.

In [19]:
# Si entrenaste el modelo y lo quieres guardar, descomentar el siguiente bloque.
if not os.path.exists('./pretrained_models'):
    os.mkdir('./pretrained_models')
biobio_w2v.save('./pretrained_models/biobio_w2v.model')


# cargar el modelo (si es que lo entrenaron desde local.)
biobio_w2v = KeyedVectors.load("./pretrained_models/biobio_w2v.model", mmap='r')


INFO - 23:26:43: saving Word2Vec object under ./pretrained_models/biobio_w2v.model, separately None
INFO - 23:26:43: not storing attribute vectors_norm
INFO - 23:26:43: not storing attribute cum_table
INFO - 23:26:44: saved ./pretrained_models/biobio_w2v.model
INFO - 23:26:44: loading Word2VecKeyedVectors object from ./pretrained_models/biobio_w2v.model
INFO - 23:26:44: loading wv recursively from ./pretrained_models/biobio_w2v.model.wv.* with mmap=r
INFO - 23:26:44: setting ignored attribute vectors_norm to None
INFO - 23:26:44: loading vocabulary recursively from ./pretrained_models/biobio_w2v.model.vocabulary.* with mmap=r
INFO - 23:26:44: loading trainables recursively from ./pretrained_models/biobio_w2v.model.trainables.* with mmap=r
INFO - 23:26:44: setting ignored attribute cum_table to None
INFO - 23:26:44: loaded ./pretrained_models/biobio_w2v.model


In [20]:
# descargar el modelo desde github
def read_model_from_github(url):
    if not os.path.exists('./pretrained_models'):
        os.mkdir('./pretrained_models')

    r = requests.get(url)
    filename = url.split('/')[-1]
    with open('./pretrained_models/' + filename, 'wb') as f:
        f.write(r.content)
    return True


[
    read_model_from_github(file) for file in [
        'https://github.com/dccuchile/CC6205/releases/download/Data/biobio_w2v.model',
    ]
]
# cargar el modelo (si es que lo entrenaron desde local.)
biobio_w2v = KeyedVectors.load("./pretrained_models/biobio_w2v.model", mmap='r')


INFO - 23:27:05: loading Word2VecKeyedVectors object from ./pretrained_models/biobio_w2v.model
INFO - 23:27:06: loading wv recursively from ./pretrained_models/biobio_w2v.model.wv.* with mmap=r
INFO - 23:27:06: setting ignored attribute vectors_norm to None
INFO - 23:27:06: loading vocabulary recursively from ./pretrained_models/biobio_w2v.model.vocabulary.* with mmap=r
INFO - 23:27:06: loading trainables recursively from ./pretrained_models/biobio_w2v.model.trainables.* with mmap=r
INFO - 23:27:06: setting ignored attribute cum_table to None
INFO - 23:27:06: loaded ./pretrained_models/biobio_w2v.model


## Tasks: Palabras mas similares y Analogías

### Palabras mas similares

Tal como dijimos anteriormente, los embeddings son capaces de codificar toda la información contextual de las palabras en vectores.

Y como cualquier objeto matemático, estos pueden operados para encontrar ciertas propiedades. Tal es el caso de las  encontrar las palabras mas similares, lo que no es mas que encontrar los n vecinos mas cercanos del vector.  

In [21]:
biobio_w2v.wv.most_similar(positive=["perro"])

INFO - 23:27:19: precomputing L2-norms of word weight vectors


[('gato', 0.7324815392494202),
 ('perrito', 0.7017662525177002),
 ('cachorro', 0.6726856231689453),
 ('canino', 0.6614428758621216),
 ('mascota', 0.6354753971099854),
 ('animal', 0.6341222524642944),
 ('gatito', 0.6259311437606812),
 ('felino', 0.622412919998169),
 ('perros', 0.6207761764526367),
 ('perra', 0.5834704041481018)]

In [22]:
biobio_w2v.wv.most_similar(positive=["Perú"])

[('Ecuador', 0.6255874633789062),
 ('peruana', 0.582399308681488),
 ('Paraguay', 0.5646696090698242),
 ('peruano', 0.5636229515075684),
 ('Colombia', 0.5616293549537659),
 ('Uruguay', 0.5335642099380493),
 ('Martín_Vizcarra', 0.5327112078666687),
 ('peruanos', 0.5254102945327759),
 ('Lima', 0.5234850645065308),
 ('Brasil', 0.5057570934295654)]

In [23]:
biobio_w2v.wv.most_similar(positive=["trump"])

KeyError: "word 'trump' not in vocabulary"

In [24]:
biobio_w2v.wv.most_similar(positive=["Trump"])

[('Casa_Blanca', 0.709988534450531),
 ('Donald_Trump', 0.7093803882598877),
 ('mandatario_estadounidense', 0.7046915292739868),
 ('inquilino', 0.678024411201477),
 ('administración_Trump', 0.6302800178527832),
 ('Bolton', 0.6201831102371216),
 ('Unidos', 0.6197685599327087),
 ('Washington', 0.6131006479263306),
 ('presidente_estadounidense', 0.6014897227287292),
 ('Unidos_Donald', 0.5976207256317139)]

In [25]:
biobio_w2v.wv.most_similar(positive=["Pizza"])

[('Hut', 0.9047655463218689),
 ('Telepizza', 0.8243373036384583),
 ('ATT', 0.7196983098983765),
 ('Linio', 0.6911829113960266),
 ('Homecenter', 0.6828977465629578),
 ('Unimarc', 0.6740168333053589),
 ('Natura', 0.6694700717926025),
 ('Nestlé', 0.6646097302436829),
 ('Coffee', 0.6622934937477112),
 ('Sodimac', 0.6596288681030273)]

In [26]:
biobio_w2v.wv.most_similar(positive=["pizza"])

[('hamburguesas', 0.6893606185913086),
 ('cafeterías', 0.6606760025024414),
 ('degustaciones', 0.6389386653900146),
 ('repartidor', 0.6389126777648926),
 ('pizzas', 0.6339085102081299),
 ('platos', 0.6290442943572998),
 ('arroz', 0.6215819716453552),
 ('hamburguesa', 0.6195734739303589),
 ('vodka', 0.6181467771530151),
 ('chocolates', 0.616828441619873)]

In [27]:
biobio_w2v.wv.most_similar(positive=["Uber"])

[('Cabify', 0.7779495716094971),
 ('Eats', 0.700801432132721),
 ('DiDi', 0.676181435585022),
 ('Rappi', 0.6054359078407288),
 ('Conductores', 0.5858488082885742),
 ('aplicaciones', 0.5700352787971497),
 ('Beat', 0.566635251045227),
 ('app', 0.5640519857406616),
 ('choferes', 0.5415352582931519),
 ('taxistas', 0.5351073741912842)]

In [28]:
biobio_w2v.wv.most_similar(positive=["Huawei"])

[('ZTE', 0.7025798559188843),
 ('telecomunicaciones', 0.639496922492981),
 ('Wanzhou', 0.617560863494873),
 ('5G', 0.6000876426696777),
 ('Meng', 0.5700865387916565),
 ('Pekin', 0.5595781803131104),
 ('Ren', 0.54143226146698),
 ('gigante_asiático', 0.5363011956214905),
 ('sanciones_estadounidenses', 0.5254279375076294),
 ('China', 0.5246084928512573)]

In [29]:
biobio_w2v.wv.most_similar(positive=["TVN"])

[('Televisión', 0.6506631374359131),
 ('directorio', 0.5564517974853516),
 ('Orrego', 0.48779889941215515),
 ('C5N', 0.47816959023475647),
 ('Panorama', 0.47550541162490845),
 ('Chilevisión', 0.46353697776794434),
 ('cuprífera', 0.4621236324310303),
 ('matinal', 0.45264914631843567),
 ('CHV', 0.4483409821987152),
 ('Mega', 0.44625139236450195)]

In [30]:
biobio_w2v.wv.most_similar(positive=["ultraderechista"])

[('excapitán_Ejército', 0.7039800882339478),
 ('ultraderecha', 0.7019724249839783),
 ('ultraderechista_Jair', 0.661270022392273),
 ('extrema_derecha', 0.6610966324806213),
 ('Finlandeses', 0.659309983253479),
 ('Verdaderos', 0.6557667851448059),
 ('antiinmigración', 0.6375353336334229),
 ('exmilitar', 0.636165201663971),
 ('Liga', 0.6324677467346191),
 ('Matteo_Salvini', 0.6320110559463501)]

In [31]:
biobio_w2v.wv.most_similar(positive=["Concepción"])

[('penquista', 0.6831767559051514),
 ('Talcahuano', 0.6503714919090271),
 ('Chiguayante', 0.6319462060928345),
 ('Temuco', 0.6043856143951416),
 ('Santiago', 0.6022074222564697),
 ('Penco', 0.586882472038269),
 ('Hualqui', 0.5604559779167175),
 ('Hualpén', 0.5555928945541382),
 ('Lota', 0.5550185441970825),
 ('Chillán', 0.5531082153320312)]

### Analogías

Por otra parte, la analogía consiste en comparar 3 terminos mediante una operación del estilo: 

$$palabra1 - palabra2 \approx palabra 3 - x$$

para encontrar relaciones entre estos.

Por ejemplo:

| palabra 1 (pos) |  palabra 2 (neg) |
|-----------------|------------------|
|  macri          | piñera           |
| chile           |  x               |

In [32]:
biobio_w2v.wv.most_similar(positive=["Bolsonaro", "Argentina"], negative=['Macri'], topn=10)

[('Brasil', 0.665826678276062),
 ('Jair_Bolsonaro', 0.5471663475036621),
 ('ultraderechista_Jair', 0.516360878944397),
 ('Paraguay', 0.4729083180427551),
 ('excapitán_Ejército', 0.47257742285728455),
 ('Ultraderechista', 0.4531181752681732),
 ('Colombia', 0.45093128085136414),
 ('nostálgico', 0.4260634183883667),
 ('presidente_electo', 0.42563045024871826),
 ('Perú', 0.4201669692993164)]

In [33]:
biobio_w2v.wv.most_similar(positive=["Chile", "Huawei"], negative=['China'], topn=10)

[('Falabella', 0.47030484676361084),
 ('portabilidad', 0.4300999641418457),
 ('Multicaja', 0.4203709363937378),
 ('CMR', 0.41495582461357117),
 ('Sodimac', 0.4064332842826843),
 ('Valledor', 0.3986559212207794),
 ('Telefónica', 0.39562681317329407),
 ('Ciberseguridad', 0.39511701464653015),
 ('Subtel', 0.39427271485328674),
 ('retail', 0.39312079548835754)]

### Visualizar

Para visualizar, reduciremos las 200 dimensiones a 2. Para esto, usaremos [`T-SNE`](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html)

In [34]:
NUM_EMBEDDINGS_TO_VISUALIZE = 10000

word_counts = dict()
for item in biobio_w2v.wv.vocab:
    word_counts[item]=biobio_w2v.wv.vocab[item].count
    
sorted_word_counts = {k: v for k, v in sorted(word_counts.items(), key=lambda item: item[1], reverse=True)}    

In [35]:
words_to_visualize = list(sorted_word_counts.keys())[0:NUM_EMBEDDINGS_TO_VISUALIZE]

In [37]:
import numpy as np
wv_to_visualize = np.array([biobio_w2v.wv[word] for word in words_to_visualize])
wv_to_visualize.shape

(10000, 200)

In [38]:
# Ejecutamos las transformaciones.
tsne_components = TSNE(n_components=2, verbose=True,
                  n_jobs=-1).fit_transform(wv_to_visualize)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 10000 samples in 0.200s...
[t-SNE] Computed neighbors for 10000 samples in 22.416s...
[t-SNE] Computed conditional probabilities for sample 1000 / 10000
[t-SNE] Computed conditional probabilities for sample 2000 / 10000
[t-SNE] Computed conditional probabilities for sample 3000 / 10000
[t-SNE] Computed conditional probabilities for sample 4000 / 10000
[t-SNE] Computed conditional probabilities for sample 5000 / 10000
[t-SNE] Computed conditional probabilities for sample 6000 / 10000
[t-SNE] Computed conditional probabilities for sample 7000 / 10000
[t-SNE] Computed conditional probabilities for sample 8000 / 10000
[t-SNE] Computed conditional probabilities for sample 9000 / 10000
[t-SNE] Computed conditional probabilities for sample 10000 / 10000
[t-SNE] Mean sigma: 0.324630
[t-SNE] KL divergence after 250 iterations with early exaggeration: 97.095749
[t-SNE] KL divergence after 1000 iterations: 2.501570


Extraemos la frecuencia de las palabras:

Con los nuevos vectores que nos entrego TSNE mas el vocabulario y la frecuencia del vocabulario, formamos un DataFrame.


In [39]:
tsne = pd.DataFrame({
    'x': tsne_components[:,0],
    'y': tsne_components[:,1],
    'vocab': words_to_visualize , 
})

Para la visualización, usaremos plotly. Este nos deja tener una barra interactiva que nos mostrará las 100 palabras mas parecidas a la que escribimos.

In [40]:
described_tsne = tsne.describe()
min_y = described_tsne.y['min']
max_y = described_tsne.y['max']

min_x =  described_tsne.x['min']
max_x =  described_tsne.x['max']

In [41]:
textbox = widgets.Text(description='Palabra:')


def validate(word):
    if word in tsne.vocab.values:
        return True
    else:
        return False


def response(change):

    word = textbox.value

    if (word == ''):
        with fig.batch_update():
            fig.data[0].x = tsne.x.values
            fig.data[0].y = tsne.y.values
            fig.data[0].text = tsne.vocab.values
    else:
        if validate(word):

            most_similar_words = [word]

            for word_tuple in biobio_w2v.wv.most_similar(positive=[word],
                                                         topn=100):
                if word_tuple[0] in tsne.vocab.values:
                    most_similar_words.append(word_tuple[0])

            filtered_words = [
                word in most_similar_words for word in tsne.vocab
            ]
            temp = tsne.loc[filtered_words]

            with fig.batch_update():
                fig.data[0].x = temp.x.values
                fig.data[0].y = temp.y.values
                fig.data[0].text = temp.vocab.values

In [42]:
fig = go.FigureWidget(data=[
    go.Scatter(x=tsne.x,
               y=tsne.y,
               mode='markers',
               text=tsne.vocab)
],
                      layout=go.Layout(title=go.layout.Title(
                          text="Visualización 2D Embeddings Biobio"),
                                       yaxis=dict(range=[min_y, max_y]),
                                       xaxis=dict(range=[min_x, max_x])))
fig.update_layout(
    template='plotly_dark',
    height=800,
)
container = widgets.HBox([textbox])
textbox.observe(response, names="value")

widgets.VBox([container, fig])

    'data': [{'mode': …

## Word Embeddings como características para clasificar


En esta sección, veremos como utilizar los word embeddings como característica para **clasificar nuevamente el tópico de las noticias de la radio biobio**.


Primero, obtendremos los datos y sus categorías y dejamos solo las primeras 20:

### Cargar el dataset

In [43]:
dataset = dataset_r.copy(deep=True)

In [44]:
# creamos una nueva columna titulo y contenido.
content = dataset['content'] 

# obtenemos las clases
subcategory = dataset.subcategory

# dejamos en el dataset solo contenido de la noticia y categoria
dataset = pd.DataFrame({'content': content, 'category': subcategory})

In [45]:
NUM_SAMPLES = 250

categorias_seleccionadas = [
    'america-latina', 'eeuu', 'europa', 'chile', 'region-metropolitana',
    'region-del-bio-bio', 'negocios-y-empresas', 'region-de-los-lagos',
    'actualidad-economica', 'region-de-valparaiso', 'region-de-la-araucania',
    'curiosidades', 'asia', 'region-de-los-rios', 'entrevistas', 'debates',
    'mediooriente', 'viral', 'animales', 'tu-bolsillo'
]

# filtrar solo categorias seleccionadas
dataset = dataset[dataset['category'].isin(categorias_seleccionadas)]

# balancear clases
g = dataset.groupby('category')
dataset = pd.DataFrame(
    g.apply(lambda x: x.sample(NUM_SAMPLES).reset_index(drop=True))
).reset_index(drop=True)

Ahora, transformamos cada documento del dataset en el promedio de sus embeddings.


### Dividir el dataset en training y test

In [46]:
X_train, X_test, y_train, y_test = train_test_split(dataset.content,
                                                    dataset.category,
                                                    test_size=0.33,
                                                    random_state=42)

Primero, crearemos el Transformer con el cual convertiremos el documento a vector. (puede que les sirva para la tarea...)


### Doc2vec

In [50]:
class Doc2VecTransformer(BaseEstimator, TransformerMixin):
    """ Transforma tweets a representaciones vectoriales usando algún modelo de Word Embeddings.
    """
    
    def __init__(self, model, aggregation_func):
        # extraemos los embeddings desde el objeto contenedor. ojo con esta parte.
        self.model = model.wv 
        
        # indicamos la función de agregación (np.min, np.max, np.mean, np.sum, ...)
        self.aggregation_func = aggregation_func

    def simple_tokenizer(self, doc, lower=False):
        """Tokenizador. Elimina signos de puntuación, lleva las letras a minúscula(opcional) y 
           separa el tweet por espacios.
        """
        if lower:
            doc.translate(str.maketrans('', '', string.punctuation)).lower().split()
        return doc.translate(str.maketrans('', '', string.punctuation)).split()

    def transform(self, X, y=None):
        
        doc_embeddings = []
        
        for doc in X:
            # tokenizamos el documento. Se llevan todos los tokens a minúscula. 
            # ojo con esto, ya que puede que tokens con minúscula y mayúscula tengan
            # distintas representaciones
            tokens = self.simple_tokenizer(doc, lower = True) 
            
            selected_wv = []
            for token in tokens:
                if token in self.model.vocab:
                    selected_wv.append(self.model[token])
                    
            # si seleccionamos por lo menos un embedding para el tweet, lo agregamos y luego lo añadimos.
            if len(selected_wv) > 0:
                doc_embedding = self.aggregation_func(np.array(selected_wv), axis=0)
                doc_embeddings.append(doc_embedding)
            # si no, añadimos un vector de ceros que represente a ese documento.
            else: 
                print('No pude encontrar ningún embedding en el tweet: {}. Agregando vector de ceros.'.format(doc))
                doc_embeddings.append(np.zeros(self.model.vector_size)) # la dimension del modelo 

        return np.array(doc_embeddings)
    
    def fit(self, X, y=None):
        return self


### Definimos el pipeline


Usaremos la transformación que creamos antes mas una regresión logística.

In [51]:
clf = LogisticRegression(max_iter=1000000)

doc2vec_mean = Doc2VecTransformer(biobio_w2v, np.mean)
doc2vec_sum = Doc2VecTransformer(biobio_w2v, np.sum)
doc2vec_max = Doc2VecTransformer(biobio_w2v, np.max)

pipeline = Pipeline([('doc2vec', doc2vec_sum), ('clf', clf)])

In [52]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('doc2vec',
                 Doc2VecTransformer(aggregation_func=<function sum at 0x7f1f8c0a5b80>,
                                    model=<gensim.models.keyedvectors.Word2VecKeyedVectors object at 0x7f1f1e299070>)),
                ('clf', LogisticRegression(max_iter=1000000))])

**Predecimos y evaluamos:**

In [53]:
y_pred = pipeline.predict(X_test)

In [54]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[50  0  0  0  9  0  1  2  0  0 15  2  0  0  0  0  0 12  0]
 [ 0 68  0  1  5  1  5  0  0  2  0  1  1  0  1  0  1  1  2]
 [ 0  0 53  0  0  5  1  0  2  0  0  0  1  0  1  0  0  0 12]
 [ 1  2  3 54  0  5  7  0  2  1  0  0  0  0  0  1  0  1  1]
 [ 4  0  0  1 56  1  0  2  1  0  2  7  3  1  3  3  8  9  0]
 [ 2  0  2  4  0 49  3  1  3  1  2  0  0  0  0  1  1  1 10]
 [ 2  3  2 11  0  1 52  0  7  4  1  0  0  0  0  0  0  0  3]
 [ 0  1  0  0  8  0  0 61  0  0  1  1  0  0  1  1  1  0  0]
 [ 1  2  1  3  0  3  4  0 70  3  0  0  0  0  0  0  0  0  1]
 [ 0  1  0  5  0  1 12  0  6 60  0  0  0  0  0  0  0  0  0]
 [13  0  0  0  3  2  0  1  1  0 39  0  0  0  0  5  0 14  0]
 [ 0  0  0  0  4  0  0  0  0  0  0 60  4  6  5  6  1  0  0]
 [ 1  0  0  0  3  0  0  0  0  0  0  7 52  5  4  5  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  3  8 63  1  2  2  0  0]
 [ 0  0  0  0  6  0  0  2  0  0  3  1  3  2 40 11  8  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  3  5  5  1  1 55  4  0  2]
 [ 1  0  0  0  8  0  0  2  0  0  4  2  0

In [55]:
print(classification_report(y_test, y_pred))

                        precision    recall  f1-score   support

  actualidad-economica       0.58      0.55      0.56        91
        america-latina       0.87      0.76      0.81        89
              animales       0.77      0.71      0.74        75
                  asia       0.68      0.69      0.68        78
                 chile       0.52      0.55      0.54       101
          curiosidades       0.59      0.61      0.60        80
                  eeuu       0.60      0.60      0.60        86
           entrevistas       0.82      0.81      0.82        75
                europa       0.74      0.80      0.77        88
          mediooriente       0.85      0.71      0.77        85
   negocios-y-empresas       0.45      0.50      0.48        78
region-de-la-araucania       0.67      0.70      0.68        86
   region-de-los-lagos       0.67      0.68      0.67        77
    region-de-los-rios       0.81      0.79      0.80        80
  region-de-valparaiso       0.62      

In [56]:
pipeline.predict(
    [("Alguna noticia...")])

array(['region-de-la-araucania'], dtype=object)

## Usandolo con BoW

In [57]:
# Definimos el vectorizador para convertir el texto a BoW:
vectorizer = CountVectorizer(analyzer='word', ngram_range=(1, 2))

# Definimos el clasificador que usaremos.
clf_2 = LogisticRegression(max_iter=10000)

# Definimos el pipeline
pipeline_2 = Pipeline([('features',
                        FeatureUnion([('bow', CountVectorizer()),
                                      ('doc2vec', doc2vec_sum)])), ('clf', clf)])

In [58]:
pipeline_2.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('bow', CountVectorizer()),
                                                ('doc2vec',
                                                 Doc2VecTransformer(aggregation_func=<function sum at 0x7f1f8c0a5b80>,
                                                                    model=<gensim.models.keyedvectors.Word2VecKeyedVectors object at 0x7f1f1e299070>))])),
                ('clf', LogisticRegression(max_iter=1000000))])

In [59]:
y_pred_2 = pipeline_2.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred_2)
print(conf_matrix)

[[59  0  0  0  8  1  0  1  0  0 14  0  0  0  0  1  0  7  0]
 [ 0 69  1  2  4  1  5  0  0  1  2  1  0  0  2  0  0  0  1]
 [ 0  0 60  0  0  1  0  0  1  0  0  0  0  1  0  0  0  0 12]
 [ 0  1  4 57  0  6  5  0  3  0  0  0  0  0  0  0  0  0  2]
 [ 6  0  0  1 63  1  0  2  2  0  2  4  3  1  3  2  7  4  0]
 [ 1  0  0  5  0 51  0  1  2  0  0  0  0  0  1  0  0  2 17]
 [ 1  2  0 12  0  2 61  0  2  4  0  0  0  0  0  0  0  0  2]
 [ 0  1  0  0  1  0  0 69  0  0  1  0  0  0  2  0  1  0  0]
 [ 1  3  1  3  0  4  3  0 69  2  0  1  0  0  0  0  0  0  1]
 [ 0  1  0  3  0  2  6  0  3 69  0  0  0  0  0  0  0  0  1]
 [14  1  0  0  0  2  0  1  0  0 45  0  0  0  0  4  1 10  0]
 [ 1  0  0  0  0  0  0  0  0  0  0 74  2  5  1  1  2  0  0]
 [ 1  0  0  0  2  0  0  0  0  0  1  1 63  3  3  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  2  0 74  1  0  1  1  0]
 [ 2  0  0  0  6  0  0  0  0  0  3  2  0  1 49  8  5  0  0]
 [ 0  0  0  0  0  1  0  1  0  0  2  2  3  2  2 61  4  1  0]
 [ 1  1  0  0  4  0  0  1  0  0  2  0  0

In [60]:
print(classification_report(y_test, y_pred_2))

                        precision    recall  f1-score   support

  actualidad-economica       0.61      0.65      0.63        91
        america-latina       0.86      0.78      0.82        89
              animales       0.83      0.80      0.82        75
                  asia       0.68      0.73      0.70        78
                 chile       0.68      0.62      0.65       101
          curiosidades       0.59      0.64      0.61        80
                  eeuu       0.76      0.71      0.73        86
           entrevistas       0.91      0.92      0.91        75
                europa       0.84      0.78      0.81        88
          mediooriente       0.91      0.81      0.86        85
   negocios-y-empresas       0.53      0.58      0.55        78
region-de-la-araucania       0.84      0.86      0.85        86
   region-de-los-lagos       0.89      0.82      0.85        77
    region-de-los-rios       0.84      0.93      0.88        80
  region-de-valparaiso       0.71      

### Bias en Embeddings

In [62]:
from wefe.query import Query
from wefe.word_embedding_model import WordEmbeddingModel
from wefe.metrics import RND, WEAT

In [63]:
male_words = ['hombre', 'hombres', 'niño', 'padre', 'tío', 'abuelo', 'sobrino']
female_words = ['mujer', 'mujeres', 'niña', 'madre', 'tía', 'abuela', 'sobrina']

career = [
    'ingeniero', 'ingeniera','abogado', 'médico', 'astronauta', 'presidente',
    'investigador', 'juez', 'académico'
]

science = [
    'ciencia', 'tecnología', 'física', 'química', 'astronomía', 'biología',
    'investigación', 'computación'
]
arts = [
    'arte', 'música', 'danza', 'cocina', 'cine', 'lectura', 'escritura',
    'libros', 'libro', 'ficción', 'teatro'
]

In [64]:
'ingeniera' in biobio_w2v.wv.vocab

True

In [65]:
model = WordEmbeddingModel(biobio_w2v.wv)

In [66]:
RND().run_query(
    Query([male_words, female_words], [career], ['Hombre', 'Mujer'],
          ['Carrera']), model)

{'query_name': 'Hombre and Mujer wrt Carrera',
 'result': -0.08261020978291829,
 'results_by_word': {'ingeniero': -0.13043869,
  'astronauta': -0.12255514,
  'académico': -0.114564896,
  'abogado': -0.112694025,
  'presidente': -0.104246974,
  'investigador': -0.09778023,
  'juez': -0.06920445,
  'médico': 0.0027772188,
  'ingeniera': 0.005215287}}

In [67]:
RND().run_query(
    Query([male_words, female_words], [science], ['Hombre', 'Mujer'],
          ['Ciencia']), model)

{'query_name': 'Hombre and Mujer wrt Ciencia',
 'result': -0.02750334143638611,
 'results_by_word': {'biología': -0.050181866,
  'computación': -0.045604825,
  'física': -0.031781554,
  'investigación': -0.026688933,
  'astronomía': -0.023275137,
  'tecnología': -0.022155404,
  'química': -0.016297221,
  'ciencia': -0.004041791}}

In [68]:
RND().run_query(
    Query([male_words, female_words], [arts], ['Hombre', 'Mujer'],
          ['Arte']), model)

{'query_name': 'Hombre and Mujer wrt Arte',
 'result': -0.03800590471787886,
 'results_by_word': {'teatro': -0.075146556,
  'libros': -0.070794106,
  'arte': -0.0655961,
  'libro': -0.048403025,
  'ficción': -0.041079164,
  'música': -0.03923595,
  'danza': -0.03646016,
  'cine': -0.033591866,
  'escritura': -0.021597385,
  'cocina': -0.00086045265,
  'lectura': 0.014699817}}

### Propuesto...

- Usar su modelo de embeddings favorito para ver si mejora la clasificación: 
    
 - Fast y word2vec en español, [cortesía](https://github.com/dccuchile/spanish-word-embeddings) de los grandes del DCC
 - [Conceptnet](https://github.com/commonsense/conceptnet-numberbatch)


- Visualizar los documentos usando `doc2vec`