
# Minitarea 5


-----------------

Nombre: 

Fecha de Entrega:


## Instrucciones

- El ejercicio consiste en:

    - Responder preguntas relativas a los contenidos vistos en los vídeos y slides de las clases. 
    
    - Utilizar la librería Transformers

- La minitarea es INDIVIDUAL.

- Está demás decir que no se admiten copias, ni de código, ni de respuestas escritas. 

- La entrega debe ser por u-cursos.

- Atrasos: se descontará un punto por día hábil de atraso tanto para las mini-tareas como para las competencias.

- En el horario de auxiliar se abrirán horarios de consulta en donde podrán preguntar acerca del ejercicio y en general, de todo el curso. 

- Cada sección tiene un punto base y se evalúa sobre 6 puntos.

- Al revisar, tu código será ejecutado. Verifica que tu entrega no tenga errores.

## Preguntas Teóricas
Para estas preguntas no es necesario implementar código, pero pueden utilizar pseudo código.

### Arquitecturas de Redes Neuronales

**Pregunta 1**: Explique el principal problema de las redes Elman recurrentes. Explique cada compuerta de las redes LSTM y la GRU.  (1,5 puntos)

**Respuesta**:

El principal problema de las redes Elman, es el problema del desvancimiento del gradiente, ya que la red multiplica siempre por una matriz los estados y el input. Mientras que la LSTM considera que los estados de la red puedan ser actualizados con compuertas, es decir, que algunos estados se actualizan completamente y otros no, dependiendo de las compuertas. Estas compuertas funcionan con la función sigmoide, lo que genera salidas entre 0 y 1 siendo la mayoría saturadas en esos valores. Esta arquitectura permite que no se desvanezca el gradiente en la LSTM.

En cuanto a las compuertas en la LSTM y la GRU. Las compuertas en la LSTM son tres:

- la compuerta de olvido que se encarga de determinar cuanto se olvida de la memoria en función del estado actual y el input.
- la compuerta de input se encarga de agregar la información nueva a la memoria también en función del estado actual y el input.
- y la compuerta de salida se encarga de mostrar la salida de acuerdo a los estados ocultos. Su valor también se computa en función de la entrada y los estados ocultos pasados.

Por otro lado, la red GRU contiene solamente dos set de compuertas que también se computan en función de la entrada y el estado anterior, los cuales son:

- el primero se encarga de generar el candidato a nuevo estado.
- el segundo sirve para actualizar la memoria de la GRU.

**Pregunta 2**: Explique cuales son las diferencias entre las tres arquitecturas de sequence to sequence vistas en clases (Encoder-Decoder con RNN, Encoder-Decoder con RNN y Attention, y el Transformer) (1,5 puntos)

**Respuesta**:

- El Encoder-Decoder con RNN trata de resumir con el Encoder toda la secuencia de palabras a "traducir", y se le entrega al Decoder palabra a palabra de la secuencia, más el vector que resume el contenido de la secuencia generado por el Encoder.
- El mecanismo de atención que se agrega a la arquitectura anterior, se basa en tener todos los estados ocultos del Encoder influyendo directamente en una suma ponderada para formar un nuevo vector que represente el input completo en un contexto. La gracia de este mecanismo, es que dependiendo de la palabra en la que se encuentre la secuencia, se le prestará atención a estados en particular de la secuencia completa.
- La idea detrás del transformer, es aplicar atención a toda la estructura de una red que pueda traducir una secuencia en otra. Se basa en aplicar atención a un conjunto de embeddings de la secuencia de input para contextualizarla, y luego aplicar atención a este resultado junto con, también, una contextualización de los embeddings de las salidas que ya ocurrieron anteriormente en la red.

**Pregunta 3**: ¿Cúal es el principal diferencia entre los Embeddings contextualizados (por ejemplo BERT) vs. los Embeddings estáticos (por ejemplo Word2Vec)? (1,5 puntos)

**Respuesta**: 

La principal diferencia es que los embeddings estáticos se crean considerando la palabra sin contexto. Mientras que los embeddings contextualizados consideran las palabras que rodean a la palabra objetivo.


**Pregunta 4**: Explique en que tareas y las arquitecturas con las que se entrenan ELMO y BERT (1,5 puntos)

**Respuesta**: 

## Preguntas Prácticas:

### BERT

Lo primero es instalar las librerías necesarias.

In [1]:
!pip install transformers
from transformers import BertTokenizer, BertForNextSentencePrediction, BertForMaskedLM, BertForQuestionAnswering
import torch

     |████████████████████████████████| 778kB 4.9MB/s 
     |████████████████████████████████| 890kB 17.7MB/s 
     |████████████████████████████████| 3.0MB 32.4MB/s 
     |████████████████████████████████| 1.1MB 56.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=806b6bf5d83c0180b2c0ed95d3cc802b774716a2c3a52a1a73ed7d5ed9800c44
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


Para las preguntas que siguen, utilizaremos distintas variantes de BERT disponibles en la librería transformers. [Aquí](https://huggingface.co/transformers/model_doc/bert.html) pueden encontrar toda la documentación necesaria. El modelo pre-entrenado a utilizar es "bert-base-uncased" (salvo para question answering).

BERT es un modelo de lenguaje que fue entrenado exhaustivamente sobre dos tareas: 1) Next sentence prediction. 2) Masked language modeling. Veremos ejemplos de esto en la Auxiliar del jueves 16/07/20

#### BertForNextSentencePrediction

**Pregunta 1** (2 puntos en total): Utilizando el modelo BertForNextSentencePrediction de la librería transformers, muestre cual de las 2 oraciones es más probable que sea una continuación de la primera. (0.5 puntos cada una)

Por ejemplo:

Initial: "The sky is blue."\
A: "This is due to the shorter wavelength of blue light."\
B: "Chile is one of the world's greatest economies."

Debería retornar "La oración que continúa más probable es A", justificándolo con la evaluación de BERT.

In [2]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForNextSentencePrediction: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [17]:
# Funciones auxiliares:
def oracion_mas_probable(first,sentA,sentB):
  # Su código aquí
  encoding = tokenizer(first, sentA, return_tensors='pt')
  loss, logits1 = model(**encoding, next_sentence_label=torch.LongTensor([1]))
  print(logits1)

  encoding = tokenizer(first, sentB, return_tensors='pt')
  loss, logits2 = model(**encoding, next_sentence_label=torch.LongTensor([1]))
  print(logits2)
  if logits1[0, 0] < logits2[0, 0]:
    print("Oración B")
  elif logits1[0, 0] > logits2[0, 0]:
    print("Oración A")
  else:
    print("No estoy muy seguro")

1.1)
Initial: "My cat is fluffy."\
A: "My dog has a curling tail."\
B: "A song can make or ruin a person’s day if they let it get to them."

In [19]:
oracion_mas_probable("My cat is fluffy.",
                     "My dog has a curling tail.",
                     "A song can make or ruin a person's day if they let it get to them")

tensor([[ 6.3271, -6.2078]], grad_fn=<AddmmBackward>)
tensor([[-1.6619,  4.1543]], grad_fn=<AddmmBackward>)
Oración A


1.2)
Initial: "The Big Apple is famous worldwide."\
A: "You can add cinnamon for the perfect combination."\
B: "It is America's largest city."

In [31]:
oracion_mas_probable("The Big Apple is famous worldwide.",
                     "You can add cinnamon for the perfect combination.",
                     "It is America's largest city.")
# es raro que crea que la primera candidata tenga un valor tan alto, debe
# ser por la palabra Apple
oracion_mas_probable("Manhattan is famous worldwide.",
                     "You can add cinnamon for the perfect combination.",
                     "It is America's largest city.")
# efectivamente es por eso, o eso creo jaja

tensor([[ 5.8512, -5.3675]], grad_fn=<AddmmBackward>)
tensor([[ 5.9583, -5.5298]], grad_fn=<AddmmBackward>)
Oración B
tensor([[0.9912, 0.7807]], grad_fn=<AddmmBackward>)
tensor([[ 6.1605, -5.8469]], grad_fn=<AddmmBackward>)
Oración B


1.3)
Initial: "Roses are red."\
A: "Violets are blue."\
B: "Fertilize them regularly for impressive flowers."

In [28]:
oracion_mas_probable("Roses are red.",
                     "Violets are blue.",
                     "Fertilize them regularly for impressive flowers.")

tensor([[ 6.2807, -6.0811]], grad_fn=<AddmmBackward>)
tensor([[ 6.1220, -5.6894]], grad_fn=<AddmmBackward>)
Oración A


1.4)
Initial: "I play videogames the whole day."\
A: "They make me happy."\
B: "They make me rage."\
<sub><sup><sub><sup>No estoy tan de acuerdo :D

In [32]:
oracion_mas_probable("I play videogames the whole day.",
                     "They make me happy.",
                     "They make me rage.")
# wow, el sistema cree que los juegos te hacen agresivo jaja

tensor([[ 6.0170, -5.5856]], grad_fn=<AddmmBackward>)
tensor([[ 5.8640, -5.3698]], grad_fn=<AddmmBackward>)
Oración A


####BertForMaskedLM

**Pregunta 2** (2 puntos en total): Ahora utilizaremos BertForMaskedLM para predecir una palabra oculta en una oración. (0.5 puntos cada una)\
Por ejemplo:\
BERT input: "I want to _ a new car."\
BERT prediction: "buy"

In [82]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [96]:
# Funcion auxiliar
def palabra_mas_probable(sentence):
  # Su código aquí
  # se obtuvo desde stackoverflow
  tokenized_text = tokenizer.tokenize(sentence)
  indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
  masked_index = tokenized_text.index('[MASK]')
  
  # Create the segments tensors.
  segments_ids = [0] * len(tokenized_text)

  # Convert inputs to PyTorch tensors
  tokens_tensor = torch.tensor([indexed_tokens])
  segments_tensors = torch.tensor([segments_ids])

  # Predict all tokens
  with torch.no_grad():
      predictions = model.forward(tokens_tensor, segments_tensors)
  predicted_index = torch.argmax(predictions[0][0][masked_index]).item()
  predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]

  print(predicted_token)

2.1)
BERT input: "[CLS] I love [MASK] . [SEP]"

In [97]:
palabra_mas_probable("[CLS] I love [MASK] . [SEP]")

you


2.2)
BERT input: "[CLS] I hear that Karen is very [MASK] . [SEP]"

In [98]:
palabra_mas_probable("[CLS] I hear that Karen is very [MASK] . [SEP]")

upset


2.3)
BERT input: "[CLS] She had the gift of being able to [MASK] . [SEP]"

In [99]:
palabra_mas_probable("[CLS] She had the gift of being able to [MASK] . [SEP]")

fly


2.4)
BERT input: "[CLS] It's not often you find a [MASK] on the street. [SEP]"

In [100]:
palabra_mas_probable("[CLS] It's not often you find a [MASK] on the street. [SEP]")

car


####BertForQuestionAnswering

**Pregunta 3**: (2 puntos) Utilizando el modelo BertForQuestionAnswering pre-entrenado con 'bert-large-uncased-whole-word-masking-finetuned-squad', extraiga la respuesta a cada una de las siguientes 4 preguntas y su contexto. (0.5 puntos cada una). Recuerde cambiar el tokenizer para que coincida con el modelo.

In [101]:
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

In [102]:
# Funcion Auxiliar
def entregar_respuesta(question, text):
  inputs = tokenizer(question, text, return_tensors="pt")
  input_ids = inputs["input_ids"].tolist()[0]
  text_tokens = tokenizer.convert_ids_to_tokens(input_ids)

  answer_start_scores, answer_end_scores = model(**inputs)
  answer_start = torch.argmax(
      answer_start_scores
  )  # Get the most likely beginning of answer with the argmax of the score

  answer_end = torch.argmax(answer_end_scores) + 1  # Get the most likely end of answer with the argmax of the score
  answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end]))
  print(f"Question: {question}")
  print(f"Answer: {answer}")

3.1)

Pregunta: "When was the Battle of Iquique?"

Contexto: "The Battle of Iquique was a naval engagement that occurred between a Chilean corvette under the command of Arturo Prat and a Peruvian ironclad under the command of Miguel Grau Seminario on 21 May 1879, during the naval stage of the War of the Pacific, and resulted in a Peruvian victory."

In [103]:
entregar_respuesta("When was the Battle of Iquique?", "The Battle of Iquique was a naval engagement that occurred between a Chilean corvette under the command of Arturo Prat and a Peruvian ironclad under the command of Miguel Grau Seminario on 21 May 1879, during the naval stage of the War of the Pacific, and resulted in a Peruvian victory.")

Question: When was the Battle of Iquique?
Answer: 21 may 1879


3.2)

Pregunta: "Who won the Battle of Iquique?"

Contexto: "The Battle of Iquique was a naval engagement that occurred between a Chilean corvette under the command of Arturo Prat and a Peruvian ironclad under the command of Miguel Grau Seminario on 21 May 1879, during the naval stage of the War of the Pacific, and resulted in a Peruvian victory."

In [104]:
entregar_respuesta( "Who won the Battle of Iquique?",
                   "The Battle of Iquique was a naval engagement that occurred between a Chilean corvette under the command of Arturo Prat and a Peruvian ironclad under the command of Miguel Grau Seminario on 21 May 1879, during the naval stage of the War of the Pacific, and resulted in a Peruvian victory.")

Question: Who won the Battle of Iquique?
Answer: peruvian


3.3)

Pregunta: "Who introduced peephole connections to LSTM networks?"

Contexto: "What I’ve described so far is a pretty normal LSTM. But not all LSTMs are the same as the above. In fact, it seems like almost every paper involving LSTMs uses a slightly different version. The differences are minor, but it’s worth mentioning some of them. One popular LSTM variant, introduced by Gers & Schmidhuber (2000), is adding “peephole connections.” This means that we let the gate layers look at the cell state."

In [105]:
entregar_respuesta("Who introduced peephole connections to LSTM networks?",
                   "What I’ve described so far is a pretty normal LSTM. But not all LSTMs are the same as the above. In fact, it seems like almost every paper involving LSTMs uses a slightly different version. The differences are minor, but it’s worth mentioning some of them. One popular LSTM variant, introduced by Gers & Schmidhuber (2000), is adding “peephole connections.” This means that we let the gate layers look at the cell state.")

Question: Who introduced peephole connections to LSTM networks?
Answer: gers & schmidhuber


3.4)

Pregunta: "When is the cat most active?"

Contexto: "The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth and retractable claws adapted to killing small prey. Its night vision and sense of smell are well developed. Cat communication includes vocalizations like meowing, purring, trilling, hissing, growling and grunting as well as cat-specific body language. It is a solitary hunter but a social species. It can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small mammals. It is a predator that is most active at dawn and dusk. It secretes and perceives pheromones."

In [106]:
entregar_respuesta("When is the cat most active?",
                   "The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth and retractable claws adapted to killing small prey. Its night vision and sense of smell are well developed. Cat communication includes vocalizations like meowing, purring, trilling, hissing, growling and grunting as well as cat-specific body language. It is a solitary hunter but a social species. It can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small mammals. It is a predator that is most active at dawn and dusk. It secretes and perceives pheromones.")

Question: When is the cat most active?
Answer: dawn and dusk
